### PR TITLE
feature: Add support for SetTestOptions to runtime.  

### LINKED ISSUE #5468: Add support for SetTestOptions middleware to runtime
## Is your feature request related to a problem? Please describe.

The SDK supports a SetTestOptions event which can be used to control randomness through randomValue/randomSeed.  The emulator has been updated to emit this event, but the standard composer runtime does not have the middleware to pick up the event.

## Describe the solution you'd like

Composer runtime includes SetTestOptionsMiddleware in its adapter.

### PR DESCRIPTION
**Pull request by chrimc62**
## Description
Add support for SetTestOptions middleware so that when you set randomValue/randomSeed they are passed onto adaptive dialogs to support controlling randomness.

## Task Item
Closes #5468

### CODE REVIEW

**Review by luhan2017 — APPROVED** [review]

**Comment by cwhitten** [comment]
@chrimc62 we'll close this as we deprecate usage of the existing runtime template.

**Comment by chrimc62** [comment]
@cwhitten Sigh.  The support is still missing in the runtime which means emulator supports setting it, but we will have to create documentation on how to add to your runtime.  Looks like this has been punted since R11--any idea when it will actually be fixed?
https://github.com/microsoft/BotFramework-Composer/issues/3889

**Comment by cwhitten** [comment]
@ryanlengel do you know if this is tracked on the new runtime templates?

**Comment by ryanlengel** [comment]
@chrimc62 @cwhitten this is being tracked for the runtime at microsoft/botbuilder-dotnet#5202, which is dependent on being officially supported in the SDK at microsoft/botbuilder-dotnet#5077 (@gabog is assigned to this)

**Comment by cwhitten** [comment]
Thanks Ryan

**Pull request closed without merging**
