### PR TITLE
feat: control Flow Editor via the Electron app menu

### LINKED ISSUE #3227: Cut, copy paste appears to not work with a selected action
## Describe the bug
I'm unable to cut or copy a selected action
 
## Version
1.0.0

## Browser
- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Open a bot project that has a dialog
3. Open the dialog in the design canvas that has more than one action
4. Select an action
5. Edit.Cut or Edit.Copy
6. Click on a + sign in the design surface to paste the action
7.  Notice that paste is disabled.  Also notice that Edit.Paste from the main menu is enabled.

## Expected behavior
Expect to be able to paste the action

## Screenshots
Screen Shot 2020-05-29 at 11 13 18 AM

### PR DESCRIPTION
**Pull request by yeze322**
## Description

closes #3227 

#### Problem
In Electron app, there are a group of menu items under the system menu -> 'Edit' label which are designed to share the same functionality with Composer Toolbar (Undo/Redo/Cut/Copy/Del).
Screen Shot 2020-06-01 at 10 29 37 AM

However, they never work due to not connected to editor events.

#### Target
This PR connected Composer editor APIs with the Electron app menu bar to fix this issue.
Supported actions:
- [ ] ~~'undo'~~ (api not provided by Shell, WIP by @lei9444 )
- [ ] ~~'redo'~~ (api not provided by Shell, WIP by @lei9444 )
- [x] 'copy'
- [x] 'cut'
- [x] 'delete'
- [ ] ~~'paste'~~ (paste is available in the flyout action menu)

#### How it works
Electron app menu runs in main process; Composer web app runs in renderer process.
To connect them together, we can leverage Electron IPC mechanism to let 'main' process post messages to 'renderer' process.

```js
// main process (app menu) -> post messages
rendererWindow.webContents.send('event-name', eventData);

// renderer process (Composer webapp) -> subscribe events
ipcRenderer.on('event-name', (e, eventData) => handle(eventData));
```

## Screenshots

electron-app-menu

### CODE REVIEW

**Comment by yeze322** [comment]
@cwhitten Chris do you think it's a good solution to share those Composer APIs via the global `window` variable?

**Comment by cwhitten** [comment]
@yeze322 this seems reasonable. We wouldn't want to enable those actions if there was no current node selection, so we need to add a enabled/disabled heuristic. cc @tonyanziano

**Comment by yeze322** [comment]
Feature completed, ready for review and test.
I've tested on Windows platform.

**Comment by yeze322** [comment]
> See my earlier comment on needing to wire up a disabled/enabled heuristic. It needs to match what options are available in the authoring surface.

Investigating that. The solution is probably to let renderer process report action selection state to main process.

**Comment by yeze322** [comment]
@cwhitten I updated the code to fix UT.

Ideally, the failure on undefined `ipcMain` should be fixed by providing a mocked Electron package under `__mock__/Electron.js`, however, to make the fix simple, I just check the existence of `ipcMain`.

**Pull request merged**
