### PR TITLE
a11y: fix NavItem a11y issues

### LINKED ISSUE #2025: [Accessibility][Name, Role, Value - Bot Responses]: Aria-hidden elements contain focusable elements.
**User Experience:** 
This issue should be resolved for good coding practice as Aria-hidden elements contain focusable elements.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home.
2. Run K4W tool on the page and observe the issue in Left navigation pane.

**Actual Result:**
ARIA hidden elements contains focusable elements. Screen reader does not announce the selected/non-selected state of all controls in left navigation as screen reader only read like: Bot responses button.

**Expected Result:**
Ensures ARIA hidden elements do not contains focusable elements. Screen reader should read the selected/non-selected state of all controls in left navigation like: Bot responses button selected.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}

**Attachment:**
[MAS4.1.2_Left navigation.zip](https://github.com/microsoft/BotFramework-Composer/files/4229299/MAS4.1.2_Left.navigation.zip)
[MAS4.1.2_Bot Responses _K4W.zip](https://github.com/microsoft/BotFramework-Composer/files/4229300/MAS4.1.2_Bot.Responses._K4W.zip)
[MAS4.1.2_Bot Responses_Left Navigation_K4W.zip](https://github.com/microsoft/BotFramework-Composer/files/4229301/MAS4.1.2_Bot.Responses_Left.Navigation_K4W.zip)
[MAS4.1.2_Bot Responses_Left Navigation_Screen reader.zip](https://github.com/microsoft/BotFramework-Composer/files/4229302/MAS4.1.2_Bot.Responses_Left.Navigation_Screen.reader.zip)

### LINKED ISSUE #2040: [Accessibility][Usable-Homepage]: Whole navigation is provided with tab key within the left navigation pane.
**User Experience**
For better usability purpose, whole navigation should not be provided with tab key within the left navigation pane as it will increase the efforts of users to completely navigate with tab key & then to reach to main section.

**Test Environment**
Browser: Microsoft Edge Canary Version: 82.0.425.0 (Official build)
OS build: 2004 (19564.1005)
Screen Reader: Narrator
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. Observe the issue within the left navigation pane.

**Actual:**
Whole navigation is provided with tab key within the left navigation pane which is increasing the efforts of users to completely navigate with tab key within the complete left navigation pane & then to reach to main section.

**Expected:**
For better usability purpose, whole navigation should not be provided with tab key within the left navigation pane as it will increase the efforts of users to completely navigate with tab key & then to reach to main section. navigation should be provided with up/down arrow keys.

**MAG Guideline:** 
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7bF98F4235-B6BD-47D3-8DA4-F28B9B6FBFA8%7d&file=Guideline%20101%20%E2%80%93%20Recommended%20Assistive%20Technology%20Tools%20for%20MAS%20Testing%20of%20Microsoft%20Digital%20Properties.docx&action=default&mobileredirect=true

**Attachment:**

[Usable_Homepage_left navigation.zip](https://github.com/microsoft/BotFramework-Composer/files/4235928/Usable_Homepage_left.navigation.zip)

### PR DESCRIPTION
**Pull request by beyackle**
## Description

It was much easier to fix the problems in NavItem than to rip it out and replace it with a Nav (thanks to the still-unaddressed issues in Nav with SPA react-router-style links), so after fixing up the CSS and removing the unneeded button component, this was the result.

## Task Item

Closes #2025 
Closes #2040

## Screenshots

image

### CODE REVIEW

**Comment by beyackle** [comment]
Fixed the E2E tests, and adjusted the font size back to normal:
image

**Comment by a-b-r-o-w-n** [comment]
The other thing I notice is that the active element is offset with respect to the other links.

image

**Comment by corinagum** [comment]
@beyackle gentle ping :)

**Comment by cwhitten** [comment]
I changed the margin when active

**Comment by beyackle** [comment]
Thanks for taking care of that - this slipped my mind while I was working on the labels thing.

**Comment by beyackle** [comment]
That E2E failure is the exact same one I'm seeing on my other PR, too. The "SaveAs" task, which I haven't touched and which I was able to manually step through and it seems like it should work.

**Comment by corinagum** [comment]
I pulled this and tested locally. LGTM. 

Not sure about the failing test. @cwhitten is this related to the test failures you mentioned in our 1:1 yesterday?

**Comment by cwhitten** [comment]
Yea @a-b-r-o-w-n is fixing that

**Pull request merged**
