### PR TITLE
fix: avoid creating duplicate QNA match trigger

### LINKED ISSUE #4512: QnA authoring issues
#### 2. After selecting **Start bot** and entering QnA subscription key, you will see the following error message:

Cannot test the bot in Emulator. 

## Version

The [main](https://github.com/microsoft/BotFramework-Composer) branch as of October 23, 2020

## Browser

- [x] Chrome

## OS

- [x] Windows

## To Reproduce

Steps to reproduce the behavior: [doc](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb#start-from-qna-maker-knowledge-base).

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

1. Remove pre-created resource from bot template.
2. Add check existed QnA Trigger, avoid duplicates.

## Task Item
close #4512

### CODE REVIEW

**Comment by boydc2014** [comment]
Besides fixing the pre-setup of the bot sample, we also need to update the logic to avoid creating duplicate trigger by default, right?

**Comment by zhixzhan** [comment]
> Besides fixing the pre-setup of the bot sample, we also need to update the logic to avoid creating duplicate trigger by default, right?

Yes, I asked Lu, we don't need create duplicate trigger every time, I'm going to revert changes in bot sample, add a check before create trigger.

**Comment by zhixzhan** [comment]
> > Besides fixing the pre-setup of the bot sample, we also need to update the logic to avoid creating duplicate trigger by default, right?
> 
> Yes, I asked Lu, we don't need create duplicate trigger every time, I'm going to revert changes in bot sample, add a check before create trigger.

I still removed the pre-created code from sample bot,  that will keep new created bot always fresh.

**Comment by a-b-r-o-w-n** [comment]
@zhixzhan can you provide a more descriptive title for this pull request?

**Comment by zhixzhan** [comment]
> @zhixzhan can you provide a more descriptive title for this pull request?

Sure, updated, sorry for that.

**Review by boydc2014 — APPROVED** [review]

**Pull request merged**
