### PR TITLE
feat: Enable showTypingMiddleware in BotProject

### LINKED ISSUE #1781: We need to be able to tell the user that we are busy with SendActivity of type "typing"
**Is your feature request related to a problem? Please describe.**
We do not know how to adapt the Bot template generated by Bot composer so that in each action that the Bot performs, a method that sends the typing message event can be called.
We try this on **ComposerBot.cs**:

```
 public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            **await turnContext.ShowTypingIndicator(100);**

```
But it seems that is not working when one if the actions is busy (for example an Http get request).

**Describe the solution you'd like**
We believe that best solution would be to have a method that we could overwrite in the core of the composer, so that each time it was to process an action, this method would be called first. In it we could add "typing" by code.

**Describe alternatives you've considered**
Another alternative was having an especial Emit Event named "Bot Is Typing" or similar.

**Additional context**

### PR DESCRIPTION
**Pull request by luhan2017**
## Description

In BotProject, enable showTypingMiddleware by default.

## Task Item

fixes #1781 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change which improve code quality, clean up, add tests, etc)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Doc update (document update)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

## Screenshots

Please include screenshots or gifs if your PR include UX changes.

### CODE REVIEW

**Comment by a-b-r-o-w-n** [comment]
Do users need to be able to opt out of this by some other means rather than changing the runtime?

**Comment by cwhitten** [comment]
@luhan2017 it should also be possible to render the following lg template in a bot response to achieve the same behavior, right?
```
# SendTypingIndicator
[Activity
  Type = "typing"
]
```

**Comment by luhan2017** [comment]
> @luhan2017 it should also be possible to render the following lg template in a bot response to achieve the same behavior, right?
> 
> ```
> # SendTypingIndicator
> [Activity
>   Type = "typing"
> ]
> ```

@cwhitten , it is not that easy, the typing hint shows up depending on when there is an action need to be waited, for example: httprequest, qna request and luis request, it is not so straight forward on how to set that. So the recommendation is setting it in ShowTypingMiddleware, it will automatically take effect on all the responses. Make sense?

**Comment by luhan2017** [comment]
If we don't want to enable it by default. Another option could be we have a setting called "enableShowTypingMiddleware" in the composer setting. and our runtime can decide whether to enable it by that setting.

**Comment by cwhitten** [comment]
@luhan2017 Im aware of the constraint in order for the Activity to show, but I cannot get the Activity driven typing indicator to work at all, and I'd like to see that working. Can you confirm that it does indeed work on a HttpAction and add it to the sample?

**Comment by luhan2017** [comment]
Close this PR because we don't want to enable it by default, had commented in the issue on how to enable the showtyping feature.

**Pull request closed without merging**
