### PR TITLE
feat: Implement layout to errorCallout

### LINKED ISSUE #6395: Beautify error output for bot start
Whenever the bot fails to start (especially with ejected runtime) the error message is a JSON object not parsed.

## Describe the solution you'd like
Parse the JSON in a way it would be more readable.

image
image

### PR DESCRIPTION
**Pull request by cdonke**
## Description

Implements a parsing of the JSON error object to show a more readable message.

## Task Item
Closes #6395 

## Screenshots
| Was | Became |
| --- | --- |
| image | image  |
| image | image |

Made it in a way that:
- Unknown fields are pushed to the bottom. 
- Multiline fields are wrapped in a `<pre>` tag
- Whitelisted fields have the display name and order defined
- If it's not a JSON object, no changes are made.

Tested with the error messages I could simulate.

### CODE REVIEW

**Comment by cwhitten** [comment]
@cdonke this is awesome!

**Review by a-b-r-o-w-n — APPROVED** [review]

**Comment by a-b-r-o-w-n** [comment]
Looks great @cdonke. Thanks for the PR!

**Comment by cwhitten** [comment]
We need to make sure this doesn't affect other error types that show up here, like publishing to LUIS or QnA

**Comment by cdonke** [comment]
@cwhitten 
I test if it is JSON parsable.. if not, returns the text as is... 
I'll try to simulate the other errors and check how it goes..

**Comment by cdonke** [comment]
Publishing to LUIS wasn't affected, since it returns text:
image

QnAMaker doesn't show errors there...
It shows a pop-up with some details...

image


IT would be nice to join all the messages on the same place...

**Comment by srinaath** [comment]
Thanks @cdonke. In the upcoming sprint we are also going to push this detailed error view inside a "Outputs" tabs in the Debug drawer at the bottom. This tab would house the stdout from the runtime as well as errors that happen while starting. We will reuse your code to display errors.

**Comment by cdonke** [comment]
Great @srinaath ...
I really miss the runtime stdout (especially logging).

**Comment by a-b-r-o-w-n** [comment]
@srinaath I checked with @cwhitten and concluded that this is fine to take into main as we work towards surfacing these errors in the debug tray, so I'll merge once it goes green.

**Pull request merged**
