### PR TITLE
a11y: add callout to Onboarding toggle switch

### LINKED ISSUE #2101: [Accessibility][Functional - Settings -Onboarding]: No action is performed on activating Onboarding 'Enabled' toggle button.
**User Experience:**
For keyboard users it is difficult to perform the task if any control does not perform its functionality.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19569.1000)​​
Microsoft Edge Version: 82.0.436.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. "Bot Framework Composer" homepage will gets opened.
3. Select any of the previously created bot from "Recent Bots" or create one from the available Bots under 'Examples' and activate it.
4. Select 'Settings' from left navigation.
5. Select 'Onboarding' button available under 'Configuration'.
6. Observe the issue on activating Onboarding 'Enabled' toggle button.

**Actual Result:**
No action is performed on activating Onboarding 'Enabled' toggle button. As it is mentioned in text that 'Enabling Onboarding will restart the product tour' but no actioned is performed.

**Expected Result:**
Action should be performed on activating Onboarding 'Enabled' toggle button.

Attachment:

[Functional_Settings_Onboarding.zip](https://github.com/microsoft/BotFramework-Composer/files/4255200/Functional_Settings_Onboarding.zip)

### PR DESCRIPTION
**Pull request by beyackle**
## Description

This adds a Callout to the "Onboarding" toggle in the settings, prompting a user to go back to Design view to start the process. The callout is also read out by a screen-reader (twice, for some reason, but this is still a draft).

## Task Item

Closes #2101 

## Screenshots

image

### CODE REVIEW

**Comment by beyackle** [comment]
This definitely could use some designer eyes on it; I was just making something up that looked all right to me, but it's definitely not hard to change if I need to.

**Comment by cwhitten** [comment]
hey @DesignPolice can you look at this and comment? thanks!

**Comment by DesignPolice** [comment]
Cool,

I will make something up today, I could use a distraction. Thanks @beyackle

**Comment by DesignPolice** [comment]
okay well Friday didn't work out for fixing this... so I will try again today @beyackle 

Is this just a banner with info or clickable to take you back to Design View?

**Comment by beyackle** [comment]
As I understand it, the intent isn’t even for it to be clickable; it’s just a reminder. The existing workflow is that, once the switch is flipped, going back to Design View will start a tutorial, but right now there’s no notification of any kind that that’s what to do, or that anything has changed anywhere apart from the switch. This is especially bad for SR users, but it feels like an annoying experience for anyone.

**Comment by DesignPolice** [comment]
@cwhitten @beyackle 
Sorry for the delay, had to finish another deadline... 

I would just keep this simple... I thought about using the Purple to tie it back to Onboarding, Which Marieke may want to do, but thinking just leave that in the Onboarding.

I made one with an icon and one without. 
https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=5316%3A140

**Comment by beyackle** [comment]
> @cwhitten @beyackle
> Sorry for the delay, had to finish another deadline...
> 
> I would just keep this simple... I thought about using the Purple to tie it back to Onboarding, Which Marieke may want to do, but thinking just leave that in the Onboarding.
> 
> I made one with an icon and one without.
> https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=5316%3A140

Thanks - those look great! I'll use the one with the icon.

**Comment by DesignPolice** [comment]
I just changed the size of the icon box... to 32px - to give it 8px on both sides and between the  blue and text... @beyackle

**Comment by beyackle** [comment]
image

There's still a bug where the callout ends up attached too far to the left. This happens because the initial flip causes a "Loading" pane to appear on the right, which skews the apparent width of everything to the point where the callout decides it needs to be attached farther over. This does solve the immediate issue, though, and should be adequately close to the given design.

**Pull request merged**
