### PR TITLE
feat: extension settings and improved extension builds

### LINKED ISSUE #3995: Users can configure extension settings
From the extensions page, a user can edit extension settings via a json editor.

The UX will be modeled by the experience in VS Code. 

Extensions can provide a JSON schema describing their settings interface and Composer will add a key into the settings object with the extension name.

Example:
Extension name: 
my-cool-extension

Settings Schema:
```json
{
  "type": "object",
  "properties": {
    "someSetting": {
      "type": "string",
      "default": "foo"
    }
  }
}
```

Will produce settings object like:
```json
{
  // other settings
  "my-cool-extension": {
    "someSetting": "foo"
  }
}
```

When installing a new extension, the default settings should be automatically added to the settings file.

### LINKED ISSUE #4357: Extension APIs
TODO:
- [x] project api (#4358)
- [x] dialog api
- [x] lu api
- [x] lg api
- [x] others?

### LINKED ISSUE #4899: Provide an extension hook (front end and back) during the process of opening a bot
## Is your feature request related to a problem? Please describe.

As a developer, I would like to be able to tie into the "open bot" process and take custom actions.

For example:

* I would like to pull the latest code from Github
* I would like to check dependencies for possible updates
* I would like to take custom steps actions

## Describe the solution you'd like

I think we should create a backend extension hook that is called whenever a bot is opened.  Any registered extension could add actions to the open process that would automatically be called by Composer.

Separately, an extension should be able to provide a UI plugin that, if specified, would appear before the bot is opened. If more than one is provided, these plugins could be combined into a wizard style modal.

This would enable scenarios like:

* Automatically pull from Github or some other source on open
* Allow a user to pick from a list of available versions before opening
* Allow a user to lock/unlock a project before opening
* Allow a version check to occur, and offer the ability to update dependent packages before opening

## Additional context

We have customer feedback that tapping into the open process would enable important scenarios, such as pulling from github.

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
## Description

Combines extension settings work with improved build tooling.

## Task Item

closes #4357 
closes #4899
closes #3995

### CODE REVIEW

**Review by tonyanziano — APPROVED** [review]

**Comment by boydc2014** [comment]
@VanyLaw can you comment on will this impact the azure provision extension you are working on?

**Comment by VanyLaw** [comment]
Ok, I will take a look and try it tomorrow.

**Comment by cwhitten** [comment]
Custom build here: https://fuselabs.visualstudio.com/_apis/resources/Containers/5144901/drop?itemPath=drop%2FBotFramework-Composer-1.3.1-windows-setup.exe

**Comment by a-b-r-o-w-n** [comment]
Thanks Chris. I'm testing debugging and watching extensions now. I'll have that wrapped this morning.

**Comment by zxyanliu** [comment]
Hey @cwhitten and @a-b-r-o-w-n I am pasting [a simple e2e testing report of some core scenarios](https://microsoft-my.sharepoint.com/:x:/p/v-liyan/EfLJS99KJ8hFhPyA9l1poTsBJrjc_gPpsAdPWTzVIX8SfA?e=xe9AcJ) based on this build for your reference.  

The attached report consists of two pages: the first page gives an overview of the test results, and the second page details issues with screenshots. Hope the report will save some of your time and be helpful. - Yan

**Comment by a-b-r-o-w-n** [comment]
Thanks a lot @zxyanliu! I will look at these failing tests today.

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu I have confirmed and fixed an issue with the publishing profiles, but the issues related to custom runtimes seem to be unrelated to my change (they exist in the nightly). I've filed #5828 and #5832.

I have a new build for you to test running right now, I'll post a link when it's complete.

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu Here is a new windows build: https://fuselabs.visualstudio.com/_apis/resources/Containers/5178153/drop?itemPath=drop%2FBotFramework-Composer-1.3.1-windows-setup.exe

**Comment by zxyanliu** [comment]
@a-b-r-o-w-n Thank you for the update. I just tested using the latest Windows build you shared and the publishing issue was resolved. I also updated the [report](https://microsoft-my.sharepoint.com/:x:/p/v-liyan/EfLJS99KJ8hFhPyA9l1poTsBJrjc_gPpsAdPWTzVIX8SfA?e=xe9AcJ).

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu Were other issues resolved?

**Comment by zxyanliu** [comment]
@a-b-r-o-w-n There are still issues with custom actions, which you already reported (https://github.com/microsoft/BotFramework-Composer/issues/5832, https://github.com/microsoft/BotFramework-Composer/issues/5828). These are related to the nightly-build. There are also issues with adding a remote skill.

**Comment by a-b-r-o-w-n** [comment]
@zhixzhan Is the remote skill issue in the nightly or just in this PR? Trying to focus my efforts today on getting this PR merged. Thanks!

**Comment by zxyanliu** [comment]
@a-b-r-o-w-n I just checked and found the remote skill bug exists in the [nightly-build 214892.a16c00c](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.214892.a16c00c). I think this PR looks good from my side now.

**Review by cwhitten — APPROVED** [review]

**Pull request merged**
