### PR TITLE
chore: update server api to prevent overwrite the root dialog

### PR DESCRIPTION
**Pull request by lei9444**
## Description
Add preserveRoot to inform create project to not overwrite the root dialog

## Task Item
#minor

### CODE REVIEW

**Review by boydc2014 — APPROVED** [review]

**Comment by a-b-r-o-w-n** [comment]
What is the reason for this change? I don't see a linked issue.

**Comment by cwhitten** [comment]
@a-b-r-o-w-n this is something I worked with Dong and Leilei on for a PVA requirement

**Comment by a-b-r-o-w-n** [comment]
This probably warrants some commenting in the code because our code base isn't directly using this parameter.

**Comment by cwhitten** [comment]
I'm going to implement the client-side of this and will be sure to include some comments.

**Comment by a-b-r-o-w-n** [comment]
We should also consider typing the request body on our controller actions like in https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/server/src/controllers/extensions.ts#L55

We can then add comments on the TS properties.

**Pull request merged**
