### PR TITLE
chore: add select all to select intents modal

### LINKED ISSUE #8443: [Skills workflow] Add select all checkbox to select intent step
Add select all checkbox to the details list showing the skill's intents

image

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description

Add select all to select intents modal for connecting to a skill
image

## Task Item

close #8443

### CODE REVIEW

**Review by hatpick — CHANGES_REQUESTED** [review]
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

DetailsList has its own select all, please use that.

**Comment by alanlong9278** [comment]
> https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
> 
> DetailsList has its own select all, please use that.



> https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
> 
> DetailsList has its own select all, please use that.

As the image shows, the detail list of intents hidden the header, so i think use the default `select all` may be weired, so I add the select all checkbox in the bottom like the select intents in `export as a skill` modal

> https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
> 
> DetailsList has its own select all, please use that.

As the image shows, the detail list of intents hidden the header, so i think use the default `select all` may be weired, so I add the select all checkbox in the bottom like the select intents in `export as a skill` modal
image

**Comment by luhan2017** [comment]
@vivekkshankar to comment on this.

**Comment by hatpick** [comment]
> > https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
> > DetailsList has its own select all, please use that.
> 
> > https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
> > DetailsList has its own select all, please use that.
> 
> As the image shows, the detail list of intents hidden the header, so i think use the default `select all` may be weired, so I add the select all checkbox in the bottom like the select intents in `export as a skill` modal
> 
> > https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
> > DetailsList has its own select all, please use that.
> 
> As the image shows, the detail list of intents hidden the header, so i think use the default `select all` may be weired, so I add the select all checkbox in the bottom like the select intents in `export as a skill` modal
> image

1. default Checkbox render as circle by details list, like ur screenshot, then you have select all as a square.
2. list is getting rendered top down, and then select all you added is at the bottom, that's weird and will require extra unnecessary effort from user to find it then click it, that's inconsistent with the UX inside and outside the app.


my preferred UX: show the header and make the default select all, always visible, do the same for the other view you mentioned as well if it's the same.

**Comment by alanlong9278** [comment]
@hatpick  use the default ux of detail list, and change the select trigger modal select all ux to default ux too in pr https://github.com/microsoft/BotFramework-Composer/pull/7963

**Review by hatpick — APPROVED** [review]

**Pull request merged**
