### PR TITLE
refactor: Visual Editor - be pluggable & reorganize folder tree & adaptive-flow-renderer lib

### LINKED ISSUE #3144: Improve the engineering quality of Visual Editor
## Describe the bug
Todos:
- [ ] Refactor of `ObiEditor.tsx` due to its exploding complexity
- [ ] Clean outdated concepts such as 'Obi', 'Step', 'Rule', 'Event'. Follow SDK convention, do use 'Dialog', 'Trigger', 'Action' instead.
- [ ] Coverage of Typescript types. At least the editor's event system should be typed.
- [ ] A portable Adaptive-Visual-SDK. inputs Adaptive elements, output a visualization. Can be used outside Composer.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by yeze322**
## Description
**Objective**: Build a clear boundary between Adaptive SDK data model and Composer features.

**Key Results**
1. Better abstraction. Shaped 2 domains: SDK visual nodes features belongs to `adaptive-flow-renderer`; Composer features belongs to `adaptive-flow-editor` _(Details-1)_
4. Pluggable Visual Editor _(Details-2)_
2. Much cleaner project structure, with better folder tree, without outdated codes. Much easier to be maintained & parralleled.
3. Tackled down complicated components which were out of control (ObiEditor.tsx), potentially can fasten R10 new features' development.

#### 1. About 2 domains: `adaptive-flow-renderer` and `adaptive-flow-editor`
- `adaptive-flow-renderer`:
    - inputs a Dialog / Trigger / Action json, outputs a **readonly** flow canvas
    - without menus / selection features
- `adaptive-flow-editor`:
    - implements complicated features such as 'Fly-out Menu', 'Multi-Selection', 'Keyboard Control', 'Action CRUD'...
    - connected with Composer's Shell API, Extension API, plugins
    - composites the output canvas of `adaptive-flow-renderer` together with EdgeMenu / NodeMenu ..., becomes a full functioned Visual Editor

**Benefits**:
1. :bulb: Portability - we can potentially use `adaptive-flow-renderer` elsewhere
2. :bulb: Maintainability - hold complexity within `adaptive-flow-editor` domain, we can build more complex menus without changing the AdaptiveFlow lib.
3. :bulb: Extendibility - Editor becomes pluggable, injecting new menus/wrappers will make it work under different scenarios (editor mode, debugger mode)

**Thinking features in new domains**
Here is the whole feature list of Visual Editor mapped to these two domains:
| Adaptive - Flow Renderer | Composer - Flow Editor |
| ------------------------ | -------------------------- |
| 1. Show Adaptive Action as visual nodes  <br> 2. Schema-driven by ui schema <br> 3. Responsive layout (dynamic node size) <br> 4. Event system (the `onEvent` handler) <br> 5. Custom Action - can consume custom schema | 1. Selection effect: drag selection, double selection <br> 2. Keyboard control: Tab move, shortcuts <br> 3. '+' new action node <br> 4. '...' menu to delete action nodes <br> 5. Copy & Paste & Move <br> 6. Plugin system integration

- [x] I've checked those features above to make sure they are still functionally working
- [x] I've also checked several integrated features with Composer to make sure they were not affected
  - [x] Onboarding - show a coachmark '4 / 5' on the right side of an action
  - [x] Toolbar - Button states are synced with Visual Editor states
  - [x] Toolbar - Copy / Cut / Delete / Move
  - [x] a11y - Action node should have a 'aria-label' attr equals to its title
  - [x] a11y - The hyper link to a dialog inside `BeginDialog` could be entered by pressing <kbd>TAB</kbd>

**New features** - We have several scheduled R10 features:
1. Show new $kind (`EditAction` | `GotoAction`)
2. Zoom-in / Zoom-out
3. Debuggability - turn the task to building a new NodeWrapper
4. 'Disable' feature
  a. Show action 'disable' state
  b. Toolbar 'Disable' / 'Enable' buttons

They can be mapped into these 2 domains as well:
| Adaptive - Flow Renderer | Composer - Flow Editor |
| ------------------------ | -------------------------- |
| [1] Show new $kind <br> [4.a] Disable -> Show action 'disable' state | [2] Zoom-in / Zoom-out <br> [3] Debuggability <br> [4.b] Disable -> Composer Toolbar integration |

#### 2. About Pluggable Visual Editor 

By inputting customized renderers including , we can composite our current Visual Editor in-use:
  image

'Pluggable' is a critical feature which will help us decoupling Composer-only logic from visual sdk features. Also can empower us in the coming R10 features such as
  - Debuggability -> we need  a debug mode editor
  - 'Disable' actions -> we need to show more complicated node states beyond focus
  - Menus - better custom action menu, with search box, sorter

##### How to use
1. Prepare 3 renderers
  - EdgeMenu (fly-out menu on an edge)
  - NodeMenu (action operation menu)
  - NodeWrapper (node container)
  - (optional) ElementWrapper
2. Pass them into `<AdaptiveDialog />`:
  image

### Code Changes
This PR touched nearly every file in the visual-designer package. Most of them are file renaming / deletion / import updates because of I changed the folder structure entirely.

As a summary, changes happened on mainly 3 areas:
1. refactor: eject composer-only menus / wrappers from core visual lib to make it pluggable
    - Ejected menus/wrappers and them reprovided them via React context.
    - Made core visual-sdk lib pure by decoupling from composer context.
    - 4 abstractions `<NodeMenu />`, `<EdgeMenu />`, `<NodeWrapper />`, `<ElementWrapper />` as pluggable parts of Visual Editor
2. refactor: cleanup of `ObiEditor.tsx`. As the most complicated component in visual-editor, it's time to clean it up. 
    - Split complicated bussiness logic into 2 hooks and 1 api adapter
      - `useSelectionEffect`: drives the multi-selection feature
      - `useEditorEventApi`: drives the event system of Visual Editor
      - `mapKeyboardCommandToEditorEvent`: drives keyboard shortcuts feature
    - let 'index.tsx' absorb the rest part of 'ObiEditor.tsx'
    - remove ObiEditor completely since 'Obi' is an outdated concept
3. chore: clean up of concepts, remove unreachable code
    - Removed deprecated 'Event' / 'Rule' logic, including several components
    - Remove the outdated 'Obi' / 'type' naming convention, now prefixed by 'Adaptive' such as `AdaptiveKinds`
    - clean unreachable code, including outdated modules, never referenced helpers / classes

### TODOs:
It's not possible to finish everything in 1 PR. So the main target of this PR is set to building a clear boundary. With a better foundation, we can then make small improvements progressively.

Here are several remaining items I want to do in the future but have lower priority than R10 feautres. Just list them out:
- [ ] Better interfaces in the `adaptive-visual-sdk` lib. Ideally, we can render different levels of dialog json such as `AdaptiveTrigger`, `AdaptiveAction`, `AdaptiveActionList`, etc.
- [ ] Domain events -> let the event system covered by TS types.
- [ ] Take FlowSchema (UiSchema) type definitions back from '@bfc/extension', create a @types pkg.
- [ ] Demo page - current demo page was already broken

## Task Item
closes #3144

### CODE REVIEW

**Comment by yeze322** [comment]
Merging 'master' caused hundreds of unexpected linter changes, so I performed a force push.

**Comment by yeze322** [comment]
I have [another excellent branch](https://github.com/yeze322/BotFramework-Composer/tree/visual/ddd/Composer/packages/extensions/visual-designer/src/adaptive-sdk) to split the visual editor extension to two libs `adaptive-visual-sdk` and `composer-visual-editor`.

In my mind, the `composer-visual-sdk` could be leveraged by any other packages want to visualize an adapive json. It will provide a series of render methods and the output JSX is interactable by subscribing a unfied `onEvent` handler.

In that branch, the project structure looks much cleaner but it changed almost every file, so I'm wondering if we want to take that kind of change, like a package wise refactor @cwhitten

**Comment by cwhitten** [comment]
@a-b-r-o-w-n what do you think about hooking the form semantics off of `adaptive-visual-sdk` ?

**Comment by cwhitten** [comment]
Why can't we converge the form and flow utilities off of

`adaptive-visual-sdk`

that takes dependencies on

`adaptive-flow`
`adaptive-form`

**Comment by yeze322** [comment]
@cwhitten That's a great structure, so I can rename the visual nodes part to 'adaptive-flow', as a dependency of 'adaptive-visual-sdk'. What about that?

**Comment by a-b-r-o-w-n** [comment]
@cwhitten I'm not sure I understand the proposed dependency graph. Are you suggesting that there are shared utilities between `adaptive-flow` and `adaptive-form` that should be packaged in `adaptive-visual-sdk`?

**Comment by a-b-r-o-w-n** [comment]
So would there be any shared dependencies between the two? Why package them together like that?

**Comment by cwhitten** [comment]
Why is there no schema based dependencies shared between the two?

**Comment by yeze322** [comment]
`AdaptiveFlow` depends on sdk.schema file, plus its own flow schema file; it has no dependency with `AdaptiveForm`.
`FlowEditor` relies on the @bfc/shared, @bfc/extension and plugins.

As a pure visualization lib, it's not required to pack Flow and Form together, they just render a same dialog json in different ways, they work on the same level.

The area of this PR was limited to organizing the Flow parts internally, didn't intend to change the Form part. If we want to pack them together in the future, maybe we can build a package wise dependency.

**Comment by yeze322** [comment]
Talking about what needs be shared between Form and Flow, I think it's the Adaptive data models, such as definitions of IDialog, IfCondition, SendActivity. Currently they are holding by `@bfc/shared`. Ideally, it could be come a `@types/Adaptive` package.

**Comment by yeze322** [comment]
Working on increasing the test coverage

**Comment by yeze322** [comment]
Some extra changes since Wednesday:
1. rename the package `@bfc/visual-designer` to `@bfc/adaptive-flow`, to be aligned with `@bfc/adaptive-form`
2. Increased the test coverage to 40%+

**Pull request merged**
