### PR TITLE
feat: skills page

### LINKED ISSUE #2326: Skills: Skills page to add/remove Skill manifests.
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19-?node-id=5013%3A2

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Add/edit skills in a composer configuration page.

skills will be saved to appsettings.json
looks like
```
{
  "MicrosoftAppId": "",
  "luis": {
    "name": "",
    "authoringRegion": "westus",
    "defaultLanguage": "en-us",
    "environment": "composer"
  },
  "qna": {
    "knowledgebaseid": "",
    "endpointkey": "",
    "hostname": ""
  },
 // new added
  "skill": [
    {
      "name": "Email Skill",
      "manifestUrl": "https://yuesuemailskill0207-gjvga67.azurewebsites.net/manifest/manifest-1.0.json"
    }
  ]
}

```

For botProject index result, skill info from manifestUrl will be fetched and filled into `skills` 
```
 [
     dialogs:[...]
     lgFiles:[...]
     luFiles:[...]
     settings:{...}
    // new added
     skills: [{ 
                 "manifestUrl": "https://yuesuemailskill0207-gjvga67.azurewebsites.net/manifest/manifest-1.0.json"
                 "name": "Email Skill",
                 "protocol: "BotFrameworkV3",
                 "description": "The Email skill provides email related capabilities.",
                 "endpointUrl": "https://yuesuemailskill0207-gjvga67.azurewebsites.net/api/messages",
                 "msAppId": "79432da8-0f7e-4a16-8c23-ddbba30ae85d"

             }]
 ]
```

## Task Item

close #2326 

#### Add (only manifest url is allowed)
- manifest url will be fetched in server, and auto-fill fields with the response data
Untitled

duplicate add are not allowed
image

#### Edit 
Untitled1

#### Delete
Untitled2

### CODE REVIEW

**Comment by cwhitten** [comment]
@zhixzhan why do we need to serialize the following fields in `appsettings.json` ?
```
      "name": "Email Skill",
      "description": "The Email skill provides email related capabilities and supports Office and Google calendars.",
      "endpointUrl": "https://yuesuemailskill0207-gjvga67.azurewebsites.net/api/messages",
      "msAppId": "79432da8-0f7e-4a16-8c23-ddbba30ae85d"
```

All of these fields can be retrieved from of the manifest url. I like keeping the hosted manifest data as the single source of truth.

**Comment by zhixzhan** [comment]
@cwhitten Did you mean only save those in appsettings.json
```
  "skill": [
     // if skill added by manifestUrl
    { 
      "manifestUrl": "https://yuesuemailskill0207-gjvga67.azurewebsites.net/manifest/manifest-1.0.json",
    },
     // if skill added by app configuration 
    {
      "name": "Email Skill",
      "endpointUrl": "https://yuesuemailskill0207-gjvga67.azurewebsites.net/api/messages",
      "msAppId": "79432da8-0f7e-4a16-8c23-ddbba30ae85d"
    }
  ]
```

When we need detail data (name/endpointUrl/msAppId..) from manifestUrl, 
- Option 1. Make a real-time request (to composer server) to fetch them. 
- Option 2. Fetch them when index botProject, put detail data in getBotProject response
``` 
 [
     dialogs:[...]
     lgFiles:[...]
     luFiles:[...]
     settings:{
           ...
           skill: [
                  { 
                     "manifestUrl": "not empty if add by manifest url"
                     "name": "Email Skill",
                     "endpointUrl": "https://yuesuemailskill0207-gjvga67.azurewebsites.net/api/messages",
                     "msAppId": "79432da8-0f7e-4a16-8c23-ddbba30ae85d"
                 }
          ]
     }
 ]

```

By doing so, we reach a balance of single source of truth & usage convenience.

**Comment by cwhitten** [comment]
@zhixzhan can you explain the scenario where a skill is provided via "app configuration"? I thought all skills are configured via providing a manifest url and nothing more.

**Comment by boydc2014** [comment]
> @zhixzhan can you explain the scenario where a skill is provided via "app configuration"? I thought all skills are configured via providing a manifest url and nothing more.

What zhixiang refered is here

image


We supported two ways to create, do you mean we should just disable the second approach?

**Comment by cwhitten** [comment]
We discussed this in standup today and couldn't find the scenario around "Add by App Configuration". The only way to add a skill is by adding it from a manifest url.

**Comment by zhixzhan** [comment]
Ok, get it

**Comment by zhixzhan** [comment]
@boydc2014 @cwhitten updated.

**Comment by zhixzhan** [comment]
> Some functional issues:
> 
> 1. It's possible to "connect" the same skill over and over again. We shouldn't allow this. If a Skill is already added and one attempts to add it again, it should be a no-op.
> 2. Deleting the Skill row does not delete the entry from the `skills` structure in the settings page.
> 
> We can fix this via inspection of the manifest url and the operation the user is attempting to complete.

Speak of this, how we treat a skill is duplicated?
- By manifestUrl
   One url may be different in [protocol]://[host-path][query][fragment]
   should we take [host-path] as an uniq id to avoid duplicate ?

- Or by endpoint.msAppId in manifestUrl response. 
image
The `endpoints` is a list, it may have production/test/.. endpoint,  currently I just take endpoints[0] as a skill's endpoint, it may be not very accurate. then by endpoint.msAppId to judge duplicate seems also difficult.

**Comment by cwhitten** [comment]
@zhixzhan Can we reintroduce the "name" field from the manifest into the settings page as well, so:

```
{
  "name": "Email skill",
  "manifestUrl": "http://contoso.com"
}
```

I understand that a manifest may have different endpoints. Is this a blocker for you?

**Comment by zhixzhan** [comment]
> @zhixzhan Can we reintroduce the "name" field from the manifest into the settings page as well, so:
> 
> ```
> {
>   "name": "Email skill",
>   "manifestUrl": "http://contoso.com"
> }
> ```

@cwhitten Ok, "name" looks good.

> 
> I understand that a manifest may have different endpoints. Is this a blocker for you?

No, here I just use endpoints[0] as skill's endpoint, just want bring it up be aware.

**Comment by cwhitten** [comment]
thanks for calling that out. it's important for @tdurnford's knowledge to allow the user to select an endpoint when calling the skill

**Comment by zhixzhan** [comment]
updated

**Comment by cwhitten** [comment]
E2E is failing due a flakey test. Merging.

**Pull request merged**
