### PR TITLE
fix: [#9331] Substring function contains wrong tooltip information

### LINKED ISSUE #9331: Substring function contains wrong tooltip information
## Describe the bug

On bot framework composer, hovering over the substring function shows an outdated tooltip : 

image

The substring function in fact has the following parameters : substring(string, startPos, **length**).
`endPos` is incorrect. 
Also, a length from the startPos that surpasses the length of the string will generate an out of range exception, not be taken as the max length of the string. 

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

### PR DESCRIPTION
**Pull request by ceciliaavila**
## Description

This PR fixes the tooltip description of the **_Substring_** function to reflect the current parameters.

_Note: we tested the case reported in the issue:_

> a length from the startPos that surpasses the length of the string will generate an out of range exception, not be taken as the max length of the string.

_but the exception was not thrown so we didn't update that part of the description._

## Task Item

Fixes #9331

## Screenshots

These images show the before and after.
image

### CODE REVIEW

**Review by BruceHaley — DISMISSED** [review]

**Comment by erquirogasw** [comment]
Hello @OEvgeny ,

We reach out to you because we are having issues with Prs modifying extensions in BotFramework-Composer, and we saw that you created some successful PRs updating the same packages (# 9396).
Our PRs fail with the error: YN0028-The lockfile would have been modified by this install, which is explicitly forbidden.
And we tried different approaches to build the project and generate the yarn.berry.lock file but we couldn't make it work.
We would like to know the steps you follow to build the project after updating the code of an extension, and if there's any extra configuration for the checksums to be properly updated.

Thanks!

**Comment by OEvgeny** [comment]
@erquirogasw the `yarn build:dev` command after some changes are made to shared packages usually works for me. If the sums didn't get updated, you could try removing `node_modules` from the extension package folder.

**Comment by OEvgeny** [comment]
@erquirogasw please ensure you pulled the latest version from master before updating the sums.

**Comment by OEvgeny** [comment]
This might be windows-related issue. Yarn has an issue with hash persistence across platforms unfortunately.

**Comment by ceciliaavila** [comment]
Hi @BruceHaley, we have the E2E tests failing in this PR and in a few others. Also, there's a component governance error, but we don't have access to the pipeline to understand the problem and fix it. Could you help us with this?
Thanks!

**Comment by OEvgeny** [comment]
@ceciliaavila e2e pipeline failure seem unrelated to the PR

**Comment by OEvgeny** [comment]
Should be good to go after related package lock hash updates

**Review by OEvgeny — APPROVED** [review]

**Pull request merged**
