### PR TITLE
fix: Fixed minor typo in the Composer Project ReadMe file:

### PR DESCRIPTION
**Pull request by filipelteixeira**
createCosmosDB to createCosmosDb

## Description

Found a small typo in the project generated readme file, that prevented the Cosmos DB resource to not be created, if used as described. The value is case sensitive, and is written as createCosmosDB instead of createCosmosDb.

I was provisioning the Azure infrastructure for an article I wrote about MBF and found out the Cosmos DB resource was still being created although I used the correct described value set as false.
After looking into the script code, I realized that the value had a typo, and recreated with the correct parameter name. It worked. :)

## Task Item

Didn't found an issue related to it. #minor

### CODE REVIEW

**Review by a-b-r-o-w-n — APPROVED** [review]
Thanks for the contribution!

**Comment by cwhitten** [comment]
@filipelteixeira there is now a conflict on this change. Can you address it?

**Comment by filipelteixeira** [comment]
@cwhitten reviewed and addressed:
- Removed the file on the merge overlap;
- Added the minor fix to the file in the new structure.

**Comment by cwhitten** [comment]
@filipelteixeira I don't think all the component file renames should be in this diff. 

Screen Shot 2021-04-07 at 4 32 31 PM

**Comment by filipelteixeira** [comment]
> @filipelteixeira I don't think all the component file renames should be in this diff.
> 
> Screen Shot 2021-04-07 at 4 32 31 PM

I'll close this pull request and remake the change onto the new merged main

**Pull request closed without merging**
