### PR TITLE
feat: Multiple language

### LINKED ISSUE #1726: UX | multi-language support: review and edit translations in the context of dialogs
Managed LG | UX Multi-lang support
5. Composer enables me to create bot responses in multiple languages, and allows me to review and edit translations in the context of dialogs. [p1/p2]

### LINKED ISSUE #1979: Monaco Editor color check
Hello,

I don't want to bring up old issues, but just now watching Dong present, I kept seeing some odd colors in the Monaco Editor - I believe is was in the Composer... but could have been something else.  But there was a odd "Tea" color...  anyway just want to verify what colors we are using _

this can push out to R-Whatever but just didn't want to forget about it. 

Maybe a screen grab of a few of the samples to see what they all look like.

https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=3270%3A231

Screen Shot 2020-02-10 at 4 28 41 PM

### LINKED ISSUE #2443: keep 'Edit mode' on in 'Bot Responses' when switching files
## Is your feature request related to a problem? Please describe.

I'm always frustrated when switching files in 'Bot Responses', I have to switch 'Edit mode' on every time

### LINKED ISSUE #3426: Luis model not created if BotSettings LUIS defaultLanguage is not "en-us"
## Describe the bug

When you create a bot from a template, change Bot Settings for Luis/defaultLanguage to "pt-br" and click "start bot" it does not create a conversation APP at Luis interface and gives the messgae:

**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
One or more errors occurred. Corresponding activity ID: b3c50378-4638-4fb4-9855-031b78e862cd.

When clicking in"TryAgain" it shows Publish Luis models screen, if You click "Ok" comes the message:

**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
versionId cannot be null or undefined.

## Version

Version: 1.0.1-nightly.138854.830d27b
Electron: 8.0.2
Chrome: 80.0.3987.86
NodeJS: 12.13.0
V8: 8.0.426.16-electron.0

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'New'
2. Click on 'Create from template'
3. Scroll down to 'QnA Maker and LUIS
4. Click in 'QnA Maker and LUIS
5. Click "Next"
6. Choose Any Name
7. Click "ok"
8. Go to "Bot Settings"
9. Find luis configuration
10. Change name to "anyname"
11. Change defaultLanguage to "pt-br"
12. Change "authoringkey" to your Luis authoringkey
13. Click StartBot

It shows the message:
**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
One or more errors occurred. Corresponding activity ID: b3c50378-4638-4fb4-9855-031b78e862cd.

When clicking in"Try Again" it shows Publish Luis models screen, if You do not change anything and click "Ok" comes the message:

**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
versionId cannot be null or undefined.

## Expected behavior

It should create the model in the respective language setting.

## Additional context

The name of the model created uses a notation with special characters like "(" and ")" what makes impossible to handle it on LUIS

### PR DESCRIPTION
**Pull request by zhixzhan**
### Multiple language bot file structure 
```
/coolbot
  coolbot.dialog          
  /language-generation
    /en-us
      common.en-us.lg
      coolbot.en-us.lg
    /fr-fr
      common.fr-fr.lg
      coolbot.fr-fr.lg 
  /language-understanding
    /en-us
      coolbot.en-us.lu 
    /fr-fr
      coolbot.fr-fr.lu 
  /dialogs
    /foo
      foo.dialog
      /language-generation
        /en-us
          foo.en-us.lg
        /fr-fr
          foo.fr-fr.lg
      /language-understanding
        /en-us
          foo.en-us.lu
        /fr-fr
          foo.fr-fr.lu
```

### appsettings.json adds
```
{
  ...
  defaultLanguage: string,  // default bot language
  languages: string[], // bot added languages
}
```

### client state
```
{
  locale: string; // current bot authoring language, one of `settings.languages`
}
```

### Check behaviors:
1. when add a language, lg/lu would be copied from `defaultLanuage` files.
2. when delete a language, all this language lg/lu would be delete.
3. when create/delete a dialog, all `languages` lg/lu would be created/deleted.
4. when create/delete/copy a template, this template in all `languages` lg would be create/delete/copy. (also for lu)
5. when update a template, only current authoring language lg `would not` be updated. ( also for lu ).
6. publish would publish all language Luis file.
7. `defaultLanguage`/`languages` can be modified through `app settings.json`
8. current language(bot authoring language) can be switch through setting page.
9. user can't delete default/current language.
10. user add more than one language at one time, and checked `switch to newly add ` would switch to first one of newly adds

### Recap 
CRUD would only ensure file structure align cross multilang lg/lu.
means file exist, lgTemplate exist, intent exist.

But update inside one lg template or lu intent or editing in all up view edit mode, changes would not be sync to other language files.

## Task Item

refs #3348 
close #1726
close #3426 
close #2443 
close #1979

#### Supported locale list
Untitled5

#### Select language
Untitled2

#### Add languages
Untitled5
Untitled4
#### Delete languages
Untitled3

#### All up view
Untitled5
image

### CODE REVIEW

**Comment by zhixzhan** [comment]
for locales, I found a json file, should we download it and save to composer code ? 
https://github.com/citation-style-language/locales/blob/master/locales.json

**Comment by hibrenda** [comment]
Tried out and findings:
- visual nodes does not sync with property editor loading
- add lg content for specific language, other local content will be updated as well 
image

**Comment by zhixzhan** [comment]
> Tried out and findings:
> 
> * visual nodes does not sync with property editor loading
fixed

> * add lg content for specific language, other local content will be updated as well
if add a template, other local content will also add this template, but body is '- '
if delete a template, other local content will also delete this template
if update a template body, other local content will not be updated.

>   image

**Comment by boydc2014** [comment]
Should we remove the "defaultLanguage" inside "luis" section, and use the top level "defaultLauange" to drive the luis behavior? @luhan2017 @cwhitten ?

**Comment by luhan2017** [comment]
I've tried this PR. Two comments
- @boydc2014 agreed to remove the defaultLanguage in luis and apply the same convention for the LU and LG default Language setting. I found an issue of the MultipleLanguageRecognizer to apply the languagePolicy. (https://github.com/microsoft/botbuilder-dotnet/issues/4143) 
- I thought the locale besides the bot name is the default language, actually it's not, it the Content Language. I need to guess where to set it and what does it mean. Can we edit it in UX instead of a config in appsettings? 
image

**Comment by cwhitten** [comment]
@sangwoohaan to sync with @mareekuh on where to show content language setting and default language setting

**Comment by zxyanliu** [comment]
I played with the multi-lang feature in LG authoring experience using this PR. My general feedback is as follows. Also see details in this doc. 
[yan-multi-lang feedback-lg.docx](https://github.com/microsoft/BotFramework-Composer/files/4853834/yan-multi-lang.feedback-lg.docx)

### Questions
1.	What user stories are designed for users with this new feature? 
We have a tech spec in issue #3348. Do we have a spec which details the designed user experience for this new feature? This is also important for usability testing of the feature. 
2.	What does **Default language** refer to? 
3.	What are the designed steps of the .lg authoring experience with multi-lang feature? 

### Conclusion
1.	The basic steps to set a language to author .lg files are:
a.	**Settings** -> **Bot Settings** 
b.	**Add language** -> Select a language to add
c.	Select a **Content language** 
d.	Author .lg in the **Content language** selected 
e.	Set **locale** (consistent with Content language) in **Emulator** so that .lg file be recognized
2.	There are three types of language settings:
•	**Content language** – which language you want to use to author the .lg files?
•	**Default language** – not sure what does this do.
•	**Locale** in **Emulator** – this determines the language end users interact with the bot. Needs to be consistent with the **Content language**. 
3.	Multi-lang experience is supported in both inline lg editor and Bot Responses editor. 

### Other feedback
1.	Naming
 
       

2.	After select **Add language**, the pop-up window is confusing. Why translation?

**Comment by hibrenda** [comment]
@zxyanliu 

My comments for following questions :

What user stories are designed for users with this new feature?

User scenarios: 
Globalize the Bot using multiple languages. 
- If user is using LUIS to perform natural language processing, composer will help to configure the Recognizer with a separate model for each language and the SDK will automatically select the model that matches the user's preferred locale.
- All of bot's prompts and response can be localized by using LG files stored in composer bot directory structure. 
  composer can help user to easily edit different LG language file through in-line editor and "Bot Response" all up view.


What does Default language refer to?

Default language: As bot can communicate with the user in multiple languages, so user could specify the proffered Locale to communicate with bot. If user did not specify the preferred locale, SDK will automatically select the "default language" model to recognize the user input (lu language file) and deliver corresponding bot response (lg language file) .
Content language: This is pure composer concept. During the bot development, user can choose which language resources can be localized. This includes :
- bot's prompts and bot response defined in LG file
- buit-in user utterance recognition model defined in LU file

What are the designed steps of the .lg authoring experience with multi-lang feature?
- Add language to configure bot multi-language support
- Define bot default language for runtime model selection and specify content language for composer bot authoring
- Edit in-line in property editor with corresponding locale selected
- Edit in composer LG/LU all up view for localization needs

TBD： QNA

**Comment by zhixzhan** [comment]
Selection used locale list: [locale list.txt](https://github.com/microsoft/BotFramework-Composer/files/4868096/locale.list.txt)

**Comment by zhixzhan** [comment]
Update grey out style when editor is `read-only`
image

**Comment by zhixzhan** [comment]
#### There are two dimensions decide a bots input/output language.

- Emulator(User set `client local`)      
- Bot setting  (Developer set `defaultLanguage`)

Priority is Emulator > Bot settings

`locale` in Emulator can set to any lang in settings.languages, if not set it, Emulator will use settings.defaultLanguage

One more thing need to pay attention is `Content language` concept only exit at Composer side used to author bot.
Bot running part only have `DefaultLanguage` & `languages` concept.

#### And two dimensions of language in composer side
- Application/Composer language
- Content language in setting page (current authoring bot language)

**Comment by zhixzhan** [comment]
updated with recoil

**Comment by mareekuh** [comment]
Hey all - next time please include me on these github issues so I can directly answer questions that pertain to the experience. I recall seeing parts and pieces of this flashing by in the standup but it'll help to see the context so I (or the designer responsible for the feature) can respond.

**Pull request merged**
