### PR TITLE
fix: error message in QnA KB creation

### PR DESCRIPTION
**Pull request by zxyanliu**
## Description

* Updated the error messages to be more user-friendly. See details in https://github.com/microsoft/BotFramework-Composer/issues/4448.
* Updated two target URLs to be aka links and point to the right places.
* Run `yarn l10n` script and bring resulting changes to en-US.json committed alongside it.

### Before

image
image

## Task Item

https://github.com/microsoft/BotFramework-Composer/issues/4448
#minor

### After
qna-1

### CODE REVIEW

**Review by beyackle — CHANGES_REQUESTED** [review]
This PR should have the `yarn l10n` script run and the resulting changes to `en-US.json` committed alongside it.

**Comment by zxyanliu** [comment]
> beyackle
This PR should have the yarn l10n script run and the resulting changes to en-US.json committed alongside it.

That's a great point, Ben! Thanks for bringing it up! 
I will update it.

**Comment by zxyanliu** [comment]
@beyackle FYI.
As suggested, I ran the `yarn l10n` script and committed the resulting changes to en-US.json. 
But why am I seeing more changes to the en-US file than what I updated? Please take a look.

**Comment by beyackle** [comment]
> @beyackle FYI.
> As you suggested, I ran the `yarn l10n` script and committed the resulting changes to en-US.json.
> But why am I seeing more changes to the en-US file than what I updated? Please take a look.

That's the result of other earlier changes that didn't run the script. I'm okay with merging these just so the file stays up-to-date without needing another PR just to take care of those.

**Comment by zxyanliu** [comment]
> > @beyackle FYI.
> > As you suggested, I ran the `yarn l10n` script and committed the resulting changes to en-US.json.
> > But why am I seeing more changes to the en-US file than what I updated? Please take a look.
> 
> That's the result of other earlier changes that didn't run the script. I'm okay with merging these just so the file stays up-to-date without needing another PR just to take care of those.

Thank you! That makes sense to me.

**Review by beyackle — APPROVED** [review]

**Pull request merged**
