### PR TITLE
doc: update title of "new bot" dialog

### LINKED ISSUE #3952: Update title of "new bot" dialog
## Is your feature request related to a problem? Please describe.

The 2nd step of the "new bot" flow currently has a modal where the project name and location are selected. However, the title of this modal is "define conversation objective" which is a legacy title from when this modal was shared with other parts of the app.

## Describe the solution you'd like

The title and description of this modal should be updated.  Consider removing "description" field which is not currently displayed anywhere.

Title: New Bot Project
Description: Specify a name and location for your new bot project. 

Screen Shot 2020-08-31 at 4 08 30 PM

### PR DESCRIPTION
**Pull request by zxyanliu**
## Description

As an experiment to refine texts in Composer UI.

* For the new bot project form:
  Create a bot project
  Specify a name, description, and location for your new bot project.

* For the new dialog form:
  Create a dialog
  Specify a name and description for your new dialog.

## Task Item

closes #3952

## Screenshots

e2e test in a draft PR:

image

image

image

### CODE REVIEW

**Comment by boydc2014** [comment]
LGTM, @liweitian can you help check this DEFINE_CONVERSATION_OBJECTIVE is used elsewhere, should we just remove it?

**Comment by liweitian** [comment]
> LGTM, @liweitian can you help check this DEFINE_CONVERSATION_OBJECTIVE is used elsewhere, should we just remove it?

remove it should be fine. @zxyanliu @boydc2014

**Comment by zxyanliu** [comment]
I reverted the commit to remove DEFINE_CONVERSATION_OBJECTIVE.
Let's not remove it for now.

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu will this close #3952?

**Review by a-b-r-o-w-n — APPROVED** [review]

**Comment by zxyanliu** [comment]
> @zxyanliu will this close #3952?

@a-b-r-o-w-n Yes. Thanks!

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu check out https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Pull request merged**
