### PR TITLE
fix: Provide more memory to Node in Docker

### PR DESCRIPTION
**Pull request by benbrown**
## Description

Add `ENV NODE_OPTIONS "--max-old-space-size=4096"` to the Dockerfile to prevent Node from running out of memory inside the container

## Task Item

refs #1669 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have functionally tested my change

### CODE REVIEW

**Comment by boydc2014** [comment]
I did some investigation on this previously, and i try to set --max-old-space-size to `2048` because that's the  default size of the allocated memory for docker-compose builder container. and i even don't have a way to change that. 

Any size bigger than that, like 4096, will result in a OOF,  because the container is asking more, but the system refuse to provide.  

So @benbrown can you test with another machine? see if this will work?

**Comment by benbrown** [comment]
@boydc2014 Are you suggesting that I need to test this on a machine with more RAM?

**Comment by boydc2014** [comment]
> @boydc2014 Are you suggesting that I need to test this on a machine with more RAM?

I was suggesting testing with a machine with less RAM, :) . I think i figured out 
image

**Comment by benbrown** [comment]
I don't understand how computers work anymore.

**Pull request merged**
