### PR TITLE
feat: Composer created bot show 'Open In Composer' in Azure

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

Upgrade Azure SDK package to support Composer created bot show 'Open In Composer' in Azure.

## Task Item
refs #minor
close https://github.com/microsoft/BotFramework-Services/issues/313

## Screenshots
image

### CODE REVIEW

**Comment by zhixzhan** [comment]
Hi @srinaath, can you help review this?

**Review by srinaath — APPROVED** [review]

**Comment by srinaath** [comment]
@zhixzhan Could you run an installer on this branch just to make sure all our core workflows still work before we merge it.

**Comment by zhixzhan** [comment]
@srinaath Verified with local electron build installer, looks fine. but the pipeline keep failed when installing some package.
https://fuselabs.visualstudio.com/Composer/_build/results?buildId=276793&view=results

**Comment by tonyanziano** [comment]
I have fixed the `Install OneAuth` step in the pipelines. The problem was that the personal access token for the OneAuth npm feed expired. I have refreshed the token.

**Comment by zhixzhan** [comment]
Thanks @tonyanziano , I checked the build pipeline found a new error `signing failed .. libEGL.dylib` on MacOS build.

**Comment by tonyanziano** [comment]
@zhixzhan Andy helped me fix the Mac build today and it should be good now. Feel free to kick off a build

**Comment by zhixzhan** [comment]
Cool @tonyanziano , retrying the build process now.

**Comment by zhixzhan** [comment]
Thanks @tonyanziano, all build have passed, @srinaath it's ok to merge it.

**Comment by zhixzhan** [comment]
Hi @tonyanziano , Can we get this merge? There are some severity alerts from npm package, not related to this change.

**Pull request merged**
