### PR TITLE
build: make docker great again

### LINKED ISSUE #1669: Running docker-composer up currently fails
## Describe the bug
Currently, docker-compose up results in a failure with a SIGKILL during the build process.

Screen Shot 2019-11-27 at 12 07 45 PM

## Version
current stable

## OS 
What operating system are you using?

- [x] macOS

## To Reproduce

1. Clone repo
2. Amend Composer/Dockerfile with `ENV NODE_OPTIONS "--max-old-space-size=4096"`
3. Run docker-composer up
4. Error!

## Expected behavior
I would expect the build to complete and for Composer to run.

## Additional context
This has been reported by a customer running Windows locally as well.

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
closes #1669

### CODE REVIEW

**Comment by cwhitten** [comment]
MDGA!

**Comment by boydc2014** [comment]
Hey @a-b-r-o-w-n, looks like i left comments in the previous PR https://github.com/microsoft/BotFramework-Composer/pull/1708#issuecomment-562385375

It fails on my side to create bot from templates in docker run.

**Comment by liweitian** [comment]
@boydc2014 @a-b-r-o-w-n runtimeFolder: Path.resolve('../../../BotProject/Templates'), in docker the runtimeFolder is app/BotProject/Template. But the folder 'Botproject' was copied to /
I think there is something wrong in the dockerfile. I am still investigating it.

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 @liweitian I will check on this today.

**Pull request merged**
