### PR TITLE
feat: Disable / Enable actions

### LINKED ISSUE #2286: Support disabled nodes in visual editor
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19-?node-id=4586%3A0

- User can disable/enable nodes (single/multi selected) nodes
- copy/paste/move does not change nodes state
- condition nodes will be taken as "one block" to be disabled 

If nodes have been disabled, corresponding LU intent will not be published as well.

### PR DESCRIPTION
**Pull request by yeze322**
## Description
closes #2286 

todos:
- [x] icons for toolbar buttons - Disable / Enable (@DesignPolice )
- [x] selection states be reflected on Disable/Enable buttons (@yeze322 )
- [x] do we need 'Disable' / 'Enable' options inside the '...' flyout menu?

## Screenshots
1. No action selected
  image
4. Both 'Disable' and 'Enable' clickable
  image
2. Only 'Disable' clickable
  image
3. Only 'Enable' clickable
  image

'Disable' Effects
image
image

### CODE REVIEW

**Comment by yeze322** [comment]
@DesignPolice Hey Marc, you were assigned because we need your input on icons.
Could you help to figure out what's the proper icons for the 'Disable' and 'Enable' button?
Can I find one in the [Office Fabric Icon](https://uifabricicons.azurewebsites.net/) lib?

**Comment by hibrenda** [comment]
My 2 cents:
Tool bar: 
- disable & enable button state should be more user friendly (eg. after one node disabled, select this node , the disable button should not be clickable)

Overall UX experience:
- if nodes disabled in visual canvas, could we reflect the state in property panel as well ? sometimes I did not notice such node is disabled but I am still editing.
- After disable action, the node will be in gray but not easy to tell it is disable gray or none-user interaction node gray (eg. set property)  as it is in gray as well. could we let user be more aware of these changes ? @sangwoohaan 

schema driven or runtime driven for nested actions
- add node into disabled if/else branch, this node will be in gray but the schema file does not add disable . so just want to confirm this is runtime driven for nested actions

**Comment by a-b-r-o-w-n** [comment]
@yeze322 what is the status of this PR? I saw you had some questions out to the design team as well as some UX feedback? Has everything been addressed? If not, can you mark this PR as draft until it is ready again?

**Comment by yeze322** [comment]
@a-b-r-o-w-n yeah, waiting for two design feedbacks:
1. Icons
2. Toolbar button UX (in our scrum the decision is to hide all unavailable buttons)

**Comment by a-b-r-o-w-n** [comment]
@yeze322 Can you address the conflict?

Also, it wasn't clear to me if this is ready for review based on yesterday's standup? Are we still waiting on something from design?

**Comment by mareekuh** [comment]
Addressed here and discussed in several standups.
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-UI-library?node-id=2968%3A27508

For more questions, feel free to reach out to me.
The design impacts toolbars across the app.

**Comment by yeze322** [comment]
@a-b-r-o-w-n just adapted to new design, now it's done.

**Pull request merged**
