### PR TITLE
chore: rename bot project setting folder (only in coding environment not on Composer installed folders)

### PR DESCRIPTION
**Pull request by liweitian**
## Description
rename bot project settings folder from botProject to projectSettings
## Task Item
#minor

### CODE REVIEW

**Comment by boydc2014** [comment]
@liweitian please fix the conflict

**Review by a-b-r-o-w-n — APPROVED** [review]

**Comment by liweitian** [comment]
Hi @a-b-r-o-w-n, this is ready to merge.

**Comment by a-b-r-o-w-n** [comment]
Let's hold off on this until the 1.3 release goes out.

**Comment by boydc2014** [comment]
@liweitian can you check this again, and take it out of draft once ready for review.

**Comment by boydc2014** [comment]
Closing this for now, this is a nice to have, as any good namings. Given we have lots of PRs already using this name and modifying the files under this folder,  it doesn't feel right to take it right now, since it might affect other critical features. 

@liweitian Let's take this as a lesson that, it's way easier to do some right at first place than to correct it afterwards.

**Pull request closed without merging**
