### PR TITLE
feat: Create TNT feedback template

### PR DESCRIPTION
**Pull request by mareekuh**
@sangwoohaan - this is a draft for adding a TNT-issue template to Composer Github, intended to live/select as a peer of a bug vs feature request.
The core objective is to prevent needing a separate place for people to list TNT items such as for LUIS we do right now here: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR_fO2PVx7nhPpmta6lCJBp9UNEQ1RDVTMUlTSDBHUFVYNk9HRDVIVEZFVSQlQCN0PWcu

The Github issue type should have:

1. - the list of things to capture (date, screenshots etc) as listed on PAGE 9 in this ppt https://microsoft-my.sharepoint-df.com/:p:/p/miprui/EVrgNO2M1hFJufQUx15OsBUBLzIpbbqIOyE3gmOgiaHSUA
2. -  the TNT category (listed on Page 10 in the same deck)
3. - the severity (page 11)
4. the ability to track items for each of the TNT categories. Not sure how to best do that - through tags so we can filter on that and plot it as a graph? Or is it better to do this as TNT-category label as part of existing bugs so it's more easily used/accessible from existing issues?

@sangwoohaan please work with Michiel on this - I do not know how to tag him.
Maybe we have a Github expert who can help/shed light on how we could make this happen. 

## Description

closes #2491

### CODE REVIEW

**Comment by mareekuh** [comment]
Adding Em and Peter who are looking into TNT templates etc. for VA

**Comment by cwhitten** [comment]
@mareekuh what do you want to do with this?

**Comment by mareekuh** [comment]
I'd be great if we can get Melanie Wang, Em ivers, Michiel Pruijsers, Jaskeerat Bedi, Quirine van Walt Meijer and Vivek Shankar added to github. This one needs to go to Michiel...

**Comment by cwhitten** [comment]
Sounds good! What is stopping them?

**Comment by emivers8** [comment]
I'm here! Is there something to review?

**Comment by mareekuh** [comment]
@emivers8 - nope sorry this is for @michiel but hes not yet on our github...
Does he need to do this or do we need to add him?

**Pull request closed without merging**
