### PR TITLE
a11y: add border to home-page buttons

### LINKED ISSUE #2127: [Accessibility][Supporting the Platform- Homepage]: Layout of few controls on Homepage is not properly visible after applying high contrast black/white theme.
**User Experience:**
User with vision disability will not get to know what exactly the control is if it will not properly visible after applying high contrast white mode.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. "Bot Framework Composer" homepage will gets opened.
3. Apply High contrast black/white theme through system settings and observe the issue on "New" button.
4. Now, "New" button and observe the issue on pane opened.

**Actual Result:**
Layout of few controls on Homepage is not properly visible after applying high contrast black/white theme.

**Expected Result:**
Layout of few controls on Homepage should be properly visible after applying high contrast black/white theme.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B672c8a8b-ed4f-463f-868f-e8131caf9b74%7D

**Attachment:**
[MAS4.3.1_Homepage.zip](https://github.com/microsoft/BotFramework-Composer/files/4266738/MAS4.3.1_Homepage.zip)

### PR DESCRIPTION
**Pull request by beyackle**
## Description

Adding a single-pixel border around the buttons on the home page makes them distinctive objects on the home page. We can't control what colors things turn in HC mode (at least not in a cross-browser way), so this seems like the next best solution.

## Task Item

closes #2127

## Screenshots
bot-buttons-with-border
bot-buttons-with-border-hc

### CODE REVIEW

**Comment by beyackle** [comment]
I'd especially like @DesignPolice to weigh in here; is this a good solution?

**Comment by DesignPolice** [comment]
Hey Ben, 

I looked at this a few weeks ago, I guess the #'s got mixed up, anyway... 

I don't have really strong opinions, I think it needs to be easy and not break a bunch of existing things.

I looked at the Dark Mode buttons in Fluent, they don't have a High Contrast version released yet. Here is what I did for the three options.  We can discuss based on the amount of work it would require.
Dark Mode link:
https://www.figma.com/file/50J0ZSgM9QyV2qSYPff4SS/Fluent-Web-Dark-Mode-Archive?node-id=0%3A2741

Figma link to my version:
https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=5584%3A0

Screen grab of mentioned Bostian Figma link

Screen Shot 2020-05-11 at 12 34 49 PM

**Comment by beyackle** [comment]
> Hey Ben,
> 
> I looked at this a few weeks ago, I guess the #'s got mixed up, anyway...
> 
> I don't have really strong opinions, I think it needs to be easy and not break a bunch of existing things.
> 
> I looked at the Dark Mode buttons in Fluent, they don't have a High Contrast version released yet. Here is what I did for the three options. We can discuss based on the amount of work it would require.
> Dark Mode link:
> https://www.figma.com/file/50J0ZSgM9QyV2qSYPff4SS/Fluent-Web-Dark-Mode-Archive?node-id=0%3A2741
> 
> Figma link to my version:
> https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=5584%3A0
> 
> Screen grab of mentioned Bostian Figma link
> 
> Screen Shot 2020-05-11 at 12 34 49 PM

I saw that, but the problem is that there's no supported standard for a browser to actually detect high-contrast mode and keep the colors in place. Edge has a special extension for it, but that's it; any solution using that extension would only ever work in Edge under Windows. Since we can't control what the colors do in high-contrast mode (or even detect if high-contrast mode is on or off), we need a solution involving shapes instead.

**Comment by DesignPolice** [comment]
Ah okay - no worries, well then if we can get some outlines, and some way to distinguish focus and thing we can go with that. No worries this close to a launch. Thanks Ben

**Comment by beyackle** [comment]
image
Here's how the focus indicator looks in high-contrast mode. This change is literally just a normal border around the element; there's nothing fancy going on, so focus indication will work as well as it usually does.

**Comment by DesignPolice** [comment]
alright well, if that is how it looks on the other buttons lets just go with that... I can see a visual pass of the different modes in my future... but if this will make our a11y peeps happy then I can live with it as well.

**Comment by beyackle** [comment]
Note: those failing checks are a known security issue in lodash and nothing to do with this particular change.

**Pull request merged**
