### PR TITLE
fix: support the cross train corner case

### PR DESCRIPTION
**Pull request by lei9444**
## Description
1. for beginDialog in OnBeginDialog trigger
`main.lu: {dia1.lu: ""}`

2. for OnIntent(Name=IntentB) in this trigger, just an SendActivity action
config will be like `main.lu: {'':"IntentB"}`

3. ignore the local intent

But the config don't support multiple intent triggers -> 1 dialog now, I have create a issue https://github.com/microsoft/botframework-cli/issues/713

## Task Item
refs #2520

### CODE REVIEW

**Comment by boydc2014** [comment]
Looks good to me, @feich-ms can you also help verify the behavior here?

**Comment by feich-ms** [comment]
@lei9444 issue https://github.com/microsoft/botframework-cli/pull/714 is fixed here https://github.com/microsoft/botframework-cli/pull/714. Maybe you can wait for the fix in and update the bf-lu package then.

**Comment by lei9444** [comment]
@boydc2014  @feich-ms I have updated the config and package now. And test it in composer, it works well now.

**Comment by cwhitten** [comment]
@lei9444 please address conflicts

**Pull request merged**
