### PR TITLE
fix: breadcrumb resizing issue

### LINKED ISSUE #8361: [R14 bugbash] Resizing the Composer window gets ResizeObserver loop limit exceeded
Resizing Composer from full screen, I got a popup saying "ResizeObserver loop ..." ... "ResizeObserver loop limit exceeded".

What I did: 
Composer was on its "Home" page.
The window was maximized on my computer screen.
I moved it over to my external monitor. It maximized itself.
I clicked the resize button in top right corner. Error occurred.

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

set breadcrumb width to (85%, 15%), introduced in #7720

## Task Item
close #8361

### CODE REVIEW

**Comment by srinaath** [comment]
@zhixzhan were you able to repro the ResizeObserver Loop error and after the PR did the issue stop surfacing?

I think it still makes sense to merge the PR as we dont need to set the breadcrumb width through JS and we can take these changes in @sorgh @boydc2014

**Comment by hatpick** [comment]
Do you have a solid repro for the issue? @zhixzhan 
if using percentage width (which was both me and Srinaath recommendation in the first place) solves the original issue, please go with it, it's better than manual calculations in JS.

**Comment by beyackle** [comment]
I agree with the above - if this does solve the ResizeObserver issue, it should be approved and merged. I'm having trouble reproing the original bug, though, so it's hard for me to know whether this does or not.

**Comment by zhixzhan** [comment]
@srinaath @hatpick @beyackle I can not repro this bug, after removing JS calculation, UI is still looks good, and should also improve page performance.

**Review by hatpick — APPROVED** [review]

**Pull request merged**
