### PR TITLE
fix: fix deploy issue while zipping the folder

### LINKED ISSUE #3301: Publishing -> Error: Only absolute URLs are supported
## Describe the bug

When creating a new Publishing Profile and copying over the settings from the provisioncomposer script and then running it it always fails with the following error;
image
image

## Version
ffde16f0

### PR DESCRIPTION
**Pull request by zidaneymar**
## Description
Fix an issue that the deploy process will get stuck at the zipping folder.

## Task Item
fixes #3301

### CODE REVIEW

**Comment by zidaneymar** [comment]
@boydc2014 @VanyLaw 
I find a way to resolve this issue without replacing the zipping library.
I remove the "@bfc/libs/bot-deploy": "../../packages/lib/bot-deploy" in package.json of azurePublish plugin, and everything starts to work fine, but not sure about the reason.
image

**Comment by boydc2014** [comment]
> @boydc2014 @VanyLaw
> I find a way to resolve this issue without replacing the zipping library.
> I remove the "@bfc/libs/bot-deploy": "../../packages/lib/bot-deploy" in package.json of azurePublish plugin, and everything starts to work fine, but not sure about the reason.
> image


Good to see we don't have to replace a package without knowing the root cause.

**Comment by zidaneymar** [comment]
Revert the previous commit and fix the path importing in azure publish plugin, previous style leads to the unexpetect behavior in zipping runtime process.

**Comment by lei9444** [comment]
I create an electron installer. But electron app can't load the azurePublish plugin. Maybe it's not a good solution

**Comment by boydc2014** [comment]
> I create an electron installer. But electron app can't load the azurePublish plugin. Maybe it's not a good solution

OK, @zidaneymar let's revert again back to use zip-folder and get the release out, then later figure out why `archiver` is not working.

**Comment by boydc2014** [comment]
@cwhitten After digging into this issue whole day trying to figure out why previous "archiver" not working, Qi and Leilei located the issue is related to the way the package is referred, as Qi stated above, but simply change that will break Electron case. So Qi revert back again to use zip-folder. 

I think this one is good to go now, we will leave the investigation later.

**Comment by zidaneymar** [comment]
close, have a better solution

**Comment by boydc2014** [comment]
> close, have a better solution

Can you link the better solution here?

**Comment by boydc2014** [comment]
Close this in favor of https://github.com/microsoft/BotFramework-Composer/pull/3536

**Pull request closed without merging**
