### PR TITLE
fix: Update Blank bot to Empty bot

### LINKED ISSUE #6978: "Blank Bot" template created bot called "empty"
## Describe the bug

Create a new bot, selecting the "Blank Bot" template. 

On the next screen (see screen shot), the default bot name is "empty". I would expect this to be "blank". Having the name default to "empty" doesn't seem correct.

## Version
Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on "Create a new bot"
2. Select the "Blank Bot" template
3. Observe the name of your new bot is "empty"
4. Wonder what "empty" was? 

## Expected behavior

I would expect my bot to be name "blank". Although, truth be told, that's not a great default name. 

## Screenshots

image

image

### PR DESCRIPTION
**Pull request by cleemullins**
Following the longstanding ASP.Net tradition, we must change this to "Empty Bot", just like ASP.Net does for new projects. 

Blank Bot, while it aligns with Powerpoint, is a graphical canvas, not a development term.

## Description

The name of "Blank bot" doesn't align with ASP.Net and/or other development ecosystems. 

## Task Item

Fixes #6978

### CODE REVIEW

**Comment by clearab** [comment]
Yes please!

**Comment by clearab** [comment]
@benbrown I thought this was refactored into a separate file that was being served from the Composer repo, rather than coded into Composer itself?

**Comment by pavolum** [comment]
It still uses the hardcoded sort order as a back up if the api call so this PR is still valid

**Review by pavolum — APPROVED** [review]

**Comment by cwhitten** [comment]
Closing as fixed by Peter in the templates project

**Pull request closed without merging**
