### PR TITLE
fix: 431 error when publish

### LINKED ISSUE #5467: Problem publishing
## Describe the bug

Unable to publish bot to azure using bot composer. It spins indefinitely with no status update and no error in the application... There is only an error in the console.. HTTP status code 431 Request Header Fields Too Large.

I tried using newer nightly build.. but I am also unable to uninstall bot composer.. When I launch the uninstaller it comes with NSIS error

## Version

Bot composer V 1.3

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Publish menu within Bot Framework Composer
2. Click on Publish Bot
3. Bot is never published
4. Error is in the console in developer tools

## Expected behavior

Expected the bot to be published as an azure web app

## Screenshots

image

image

### PR DESCRIPTION
**Pull request by VanyLaw**
## Description
fix 431 header too large error when publishing by setting max http header size in server.

## Task Item

close #5467 

## Screenshots
Use user's token to test, won't return 431.
image

### CODE REVIEW

**Review by luhan2017 — APPROVED** [review]

**Comment by yeze322** [comment]
shall we take this fix in the patch release? @cwhitten @boydc2014

**Comment by tiagonmas** [comment]
I installed the nightly build [df53a98](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.204049.df53a98) and staill get the error 
image

**Comment by kalebk** [comment]
Also getting error after installing nightly build

**Comment by cwhitten** [comment]
@tiagonmas & @kalebk can you please try the following:

1. Open a shell (cmd, etc)
2. Insert the following environment variable & value into the shell: DEBUG=composer*
3. Start Composer from the shell process

This should start Composer normally with additional logging to the server's stdout. After doing this can you run through the Provisioning experience again and paste the logs you see when running into this error?

**Comment by tiagonmas** [comment]
Hi,
Here is the output:

```
GET /plugin-host.html 200 3.098 ms - 997
GET /api/extensions/azurePublish/azurePublish 304 2.564 ms - -
OneAuth Version 1.15.0 (com.microsoft.BotFrameworkComposer)
[OneAuth:Warning:9a8hm:d8e8af45-2cda-48cd-a92e-8f0e4aa8a40b] HTTP status: 403
[OneAuth:Warning:9a8hm:d8e8af45-2cda-48cd-a92e-8f0e4aa8a40b] HTTP status: 403
[OneAuth:Error:835v1:d8e8af45-2cda-48cd-a92e-8f0e4aa8a40b] (Code:2001) The resource is forbidden.
[OneAuth:Error:835v1:d8e8af45-2cda-48cd-a92e-8f0e4aa8a40b] (Code:2001) The resource is forbidden.
[OneAuth:Warning:96w1t:d8e8af45-2cda-48cd-a92e-8f0e4aa8a40b] Failed to get profile image from Graph
[OneAuth:Warning:96w1t:d8e8af45-2cda-48cd-a92e-8f0e4aa8a40b] Failed to get profile image from Graph
GET /api/auth/getAccessToken?targetResource=https%3A%2F%2Fmanagement.core.windows.net%2F 200 46412.608 ms - -
GET /api/provision/39162.04744549128/azurePublish/resources 304 283.892 ms - -
GET /api/auth/getAccessToken?targetResource=https%3A%2F%2Fmanagement.core.windows.net%2F 304 0.398 ms - -
GET /api/auth/getAccessToken?targetResource=https%3A%2F%2Fgraph.microsoft.com%2F 200 571.478 ms - -
POST /api/telemetry/events 200 0.834 ms - 2
```

**Comment by luhan2017** [comment]
@tiagonmas we just found the change on this PR will not take effect in electron app. could you try to set this environment variable before start the nightly composer build, and try again? 
```
NODE_OPTIONS="--max-http-header-size=16000"
```

**Comment by tiagonmas** [comment]
@luhan2017 it worked with that setting! :)
image

**Pull request merged**
