### PR TITLE
fix: add self contained config in dotnet publish

### LINKED ISSUE #4348: Bot App deployed by Composer cannot start
## Deploy to existing web app on azure not work

We followed below document of composer to publish bot to an existing web app instance running on azure. The publish output prompt success, but we got 502.5 response.
* https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-to-existing-azure-resources

The error of 502.5
image

The error we got from stdout log:
```
 A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in  'D:\home\site\wwwroot\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the D:\home\site\wwwroot\Microsoft.BotFramework.Composer.WebApp.runtimeconfig.json file specifying the appropriate framework. 
```

After investigate further, we noticed that bot was set to OutOfProcess mode and the process of dotnet.exe didn't startup because the file deployed by composer missed **\<entry-dll\>.runtimeconfig.json.**

we can find EchoBot.runtimeconfig.json, but the the entry was set to **Microsoft.BotFramework.Composer.WebApp.dll** instead of **EchoBot.dll** in web.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Microsoft.BotFramework.Composer.WebApp.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="OutOfProcess" />
    </system.webServer>
  </location>
</configuration>
```

After we uploaded file Microsoft.BotFramework.Composer.WebApp.runtimeconfig.json then it works.

It's all good if we deploy bot to a new azure resource.
> https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-to-new-azure-resources 

## Version

We pulled the latest code from composer repo and build it in azure vm. The document link as below:
> https://docs.microsoft.com/en-us/composer/how-to-host-composer

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [ ] Windows
- [x] Ubuntu

## To Reproduce

1. Go to publish tab of composer
2. Edit the profile and set the name of existing web app to hostname field, and other required fields like appId, appPassword and access token.
3. Run publish and prompt success.
4. Go to the existing web app and access its page or **https://\<app-name\>/api/messages** then see the error

## Expected behavior

Please help to point out anything we are missing to config composer if this is not an issue of composer.

Otherwise, we expected that app published by composer should be qualified for app service requirement, like the dotnet runtime configuration file for entry assembly should be deployed to app service as well if it is self-contained.

### PR DESCRIPTION
**Pull request by zidaneymar**
## Description

Under linux environment, webapp bot couldn't be started up after dotnet publishing.
This issue only occurs at 'linux' env.
For runtime identifier: please refer to this doc: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

## Task Item
fixes #4348

### CODE REVIEW

**Review by luhan2017 — COMMENTED** [review]
Can we add an param for deployment, and default it to windows? Later if customer want to have a customized deployment (for example, linux vm), they can just set the param in the script.

**Comment by zidaneymar** [comment]
> Can we add an param for deployment, and default it to windows? Later if customer want to have a customized deployment (for example, linux vm), they can just set the param in the script.

OK, I will add it today.

**Comment by cwhitten** [comment]
@zidaneymar @luhan2017 I'd like to verify that this won't break existing publishing profiles without this new shape, and allow users with old publishing profiles to add this new parameter.

**Comment by zidaneymar** [comment]
Tested 4 different scenarios:
Composer hosting on linux publish to linux operating system.
Composer hosting on linux publish to windows operating system.
Composer hosting on windows publish to linux operating system.
Composer hosting on windows publish to windows operating system.

**Review by luhan2017 — APPROVED** [review]

**Comment by luhan2017** [comment]
@zxyanliu, this may need a doc update, users needs to understand what this field means and how to use it.

**Comment by zxyanliu** [comment]
> luhan2017 commented 7 hours ago
@zxyanliu, this may need a doc update, users need to understand what this field means and how to use it.

No problem, let's discuss in detail offline.

**Review by cwhitten — APPROVED** [review]

**Pull request merged**
