### PR TITLE
a11y: add labeled aria regions to pages

### LINKED ISSUE #2080: [Accessibility][Headings and Labels - Property Pane_Ask a question]: Heading structure is not correct as the name of the pane should be defined under heading tags.
**User Experience** 
Users who rely on AT will face difficulty and easily confused if the headings are not defined correctly.

**Test Environment**
Browser: Microsoft Edge Canary Version: 82.0.425.0 (Official build)
OS build: 2004 (19564.1005)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](http://localhost:3000/dialogs/Main?selected=triggers[5]&focused=triggers[5].actions[0])

**Repro Steps:** 
1. Open the above mentioned URL in EDGE and turn on narrator.
2. Navigate to already created dialog tree item and activate it. Such as- Greetings, Actions, EndDialog etc.
3. Click on "+" and select 'Ask a question'. Then select any of the available options except Oauth login.
4. Navigate to property pane appeared at right side of the screen and navigate with 'H' i.e. shortcut for Headings.
5. Observer the issue in Property Pane.

**Actual:** 
The heading of the Property Pane i.e. 'Prompt for text' edit field is not defined under heading tags.

**Expected:**
The name of the Property Pane should be defined under heading tag. So, that the user will able to navigate quickly through the heading shortcut. 'Prompt for text' edit field should be defined under heading level 1 or level i.e as <h1> or <h2>.

**Note:**
Issue is observed for all the Property Pane  appeared at right side of the screen

**MAS Impacted:** [MAS2.4.6](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0cf80872-800d-4643-90cf-0c1c3d3e6260})

**Attachment:**
MAS2 4 6_PropertyPane

### PR DESCRIPTION
**Pull request by beyackle**
## Description

Adds `role="region"` and a bunch of ARIA labels to the app, letting SR users navigate around using landmarks. This time implemented without creating any new divs, which threw the layout off.

## Task Item

closes #2080 

## Screenshots

Just to demonstrate that the UI looks exactly like it did before:
image

### CODE REVIEW

**Comment by mareekuh** [comment]
We're using Sentence cap across the product, right @zxyanliu ?
If so, can we update Bot Responses to Bot responses?

**Comment by zxyanliu** [comment]
@mareekuh I agree. It seems PVA and Azure both use sentence case for names such as a button or component.

**Comment by beyackle** [comment]
Looks like there's a merge conflict here anyway, so I can handle changing the labels to sentence-case as part of resolving that too.

**Comment by beyackle** [comment]
This has diverged enough from master that rebasing and fixing conflicts is more difficult than manually reapplying the (relatively small set of) changes involved. Will close this one and reopen a new PR when that's up.

**Comment by beyackle** [comment]
See #3259 for the new version of this.

**Pull request closed without merging**
