### PR TITLE
chore: Use check box to select items ux

### LINKED ISSUE #7780: [UI bug] [Skills] Select all checkbox not visible in select dialog and trigger screen
image

**Expected UI:** 
- Replace circular checkbox with standard checkbox control
- Place select all checkbox in-line as shown in mock
- Select all by default

image

### PR DESCRIPTION
**Pull request by alanlong9278**
## Description
Refactor `select items` ux with checkbox
image

## Task Item
fixed #7780

### CODE REVIEW

**Comment by tdurnford** [comment]
@alanlong9278 Why are you removing the details list? The details list has a prop called `onRenderCheckbox` that should allow you to pass a custom renderer where you you can use a checkbox.

**Comment by alanlong9278** [comment]
> @alanlong9278 Why are you removing the details list? The details list has a prop called `onRenderCheckbox` that should allow you to pass a custom renderer where you you can use a checkbox.

Use `onRenderCheckbox` property. Thanks

**Comment by VanyLaw** [comment]
why we remove Description column？

**Comment by lei9444** [comment]
LGTM

**Review by luhan2017 — APPROVED** [review]

**Review by hatpick — CHANGES_REQUESTED** [review]
What details list renders by default when selection mode is multiple is "checkbox", I dont think we should change the default rendering specially since it's used in other places of the app for consistency.

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

_it's a checkbox if it has a check mark in a box._

**Comment by alanlong9278** [comment]
> What details list renders by default when selection mode is multiple is "checkbox", I dont think we should change the default rendering specially since it's used in other places of the app for consistency.
> 
> https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
> 
> _it's a checkbox if it has a check mark in a box._

Use the default ux of detail list

**Review by hatpick — APPROVED** [review]

**Pull request merged**
