### PR TITLE
fix: change collection id to container id in cosmos config

### LINKED ISSUE #5027: In CosmosDB settings, collectionId should be containerId
## Describe the bug

Using the following settings:

```
  "cosmosDb": {
    "authKey": "",
    "collectionId": "",
    "cosmosDBEndpoint": "",
    "databaseId": ""
  },
```

I get the following error:

```
Unhandled exception. System.ArgumentException: ContainerId is required. (Parameter 'cosmosDbStorageOptions') at 
Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage..ctor(CosmosDbPartitionedStorageOptions cosmosDbStorageOptions) at 
Microsoft.BotFramework.Composer.WebAppTemplates.Startup.ConfigureStorage(BotSettings settings) in C:\Users\Dana.Vanhooser\AppData\Roaming\BotFrameworkComposer\hostedBots\65422.25129587016\runtime\azurewebapp\Startup.cs:line 79 at 
Microsoft.BotFramework.Composer.WebAppTemplates.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Dana.Vanhooser\AppData\Roaming\BotFrameworkComposer\hostedBots\65422.25129587016\runtime\azurewebapp\Startup.cs:line 170 at 
System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at 
System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at 
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services) at 
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection) at 
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services) at 
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services) at 
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services) at 
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services) at 
Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider() at 
Microsoft.Extensions.Hosting.HostBuilder.Build() at 
Microsoft.BotFramework.Composer.WebAppTemplates.Program.Main(String[] args) in C:\Users\Dana.Vanhooser\AppData\Roaming\BotFrameworkComposer\hostedBots\65422.25129587016\runtime\azurewebapp\Program.cs:line 16
```
But by changing it to: 
```
  "cosmosDb": {
    "authKey": "",
    "containerId": "",
    "cosmosDBEndpoint": "",
    "databaseId": ""
  },
```
It runs successfully.

## Version

1.2.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Configure Composer bot with CosmosDB settings where the value of collectionId is the name of your cosmos DB's container. Configure endpoint, databaseid and authkey as appropriate. Fails.
2. Rename `collectionId` to `containerId` and then run. Success.

## Expected behavior

Should be `containerId` instead of `collectionId`.

### PR DESCRIPTION
**Pull request by zidaneymar**
## Description
collection id is deprecated

## Task Item
fixes #5027

### CODE REVIEW

**Comment by cwhitten** [comment]
@zidaneymar what will people do with existing publishing profiles that use `collectionId` ?

**Comment by zidaneymar** [comment]
> @zidaneymar what will people do with existing publishing profiles that use `collectionId` ?

If people use the deprecated 'collection id', runtime would meet the error in #5027, actually the runtime in latest main branch is using the library with 'container id', so this pr is to align the composer settings with the runtime.

**Comment by luhan2017** [comment]
> If



> > @zidaneymar what will people do with existing publishing profiles that use `collectionId` ?
> 
> If people use the deprecated 'collection id', runtime would meet the error in #5027, actually the runtime in latest main branch is already using the library with 'container id', so this PR is to align the composer settings with the runtime.

Can we do a mitigation in the runtime part? like if there is only collection id in the settings, take the collection id as the container id? will this work? @zidaneymar

**Comment by zidaneymar** [comment]
> > > @zidaneymar what will people do with existing publishing profiles that use `collectionId` ?
> > 
> > 
> > If people use the deprecated 'collection id', runtime would meet the error in #5027, actually the runtime in latest main branch is already using the library with 'container id', so this PR is to align the composer settings with the runtime.
> 
> Can we do a mitigation in the runtime part? like if there is only collection id in the settings, take the collection id as the container id? will this work? @zidaneymar

I pushed a new change to fix this, now runtime supports both collection and container id.

**Review by cwhitten — APPROVED** [review]

**Pull request merged**
