### PR TITLE
fix: Recent bots sort and update styles

### LINKED ISSUE #7110: Home Page MRU list has confusing sort order visuals and behavior
## Describe the bug
The sort order for the MRU list of previously opened bots has misleading UI.  See screenshot for visuals.  

I'm not exactly sure what drives the MRU list sort order.  It's not recently opened.  Which is should be.  This list should be sorted by most recently opened.  This is the way office products work.  This is the way Visual Studio works.

also, there are headers for this list that indicate the list can be sorted by other columns.  This isn't the case.  

Lastly, the Name column has a sort icon displayed, and this isn't accurate, as the list isn't sorted by name. 

## Version
Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. launch Composer
2. Note the MRU header indicates that list is sorted by name.  It actually isn't.
3. Click on the headers of the MRU list, note they indicate they should be sortable, though they are not.
4. Open a previous bot project that is not the first project in the list. 
5. Click the Home icon in the left hand nav to return to the home page.  Note the bot project you opened is not at the top of the MRU list, though is is the Most Recently Used project

## Expected behavior
I would expect the MRU list to behave as other Microsoft MRU lists, e.g. Word, Visual Studio, etc.

I would also expect the headers to not be sortable, and therefore not clickable

I would expect the up arrow icon for the Name column to go away, as we don't sort by Name.

## Screenshots

Screen Shot 2021-04-19 at 12 25 28 PM

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description
1. fix recent bots sort 
2. update homepage padding styles

## Task Item
close #7110 
refs #5857 

## Screenshots
image

### CODE REVIEW

**Comment by xiyangdesign** [comment]
@zhixzhan 
Could you help make the **table header non-clickable** visually as well? i.e. **no grey color when hovered over** as in the current build (see below). Thanks!

image

**Review by tonyanziano — COMMENTED** [review]
Looks good to me. Will approve once Xi's comment is addressed.

**Comment by zhixzhan** [comment]
@xiyangdesign @tonyanziano updated

**Comment by beyackle** [comment]
Let's get this merged so we can close the outstanding issue.

**Pull request merged**
