### PR TITLE
fix: Monaco editor loader CDN js path

### LINKED ISSUE #7965: [Something went wrong...] when pressing [Show code]
## Describe the bug

I meet an issue, when I try to press [Show code], it only shows [Something went wrong] error and is always showing [Loading...].
Some other panel have similar issue.
Could you take a look? Thank you!

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Bot responses'
2. Click on 'Show code'

## Screenshots

image

### PR DESCRIPTION
**Pull request by zhixzhan**
## Description

The current CDN path seems not be able to reach( not sure for all region or just in China )
image

the loader's default  CDN path: 

image

The fix is using an API provide in @monaco-editor/loader reset it.

### Another solution 
Copy all remote js icon font to locale, PR #5547

## Task Item
close #7965 
refs #7833

### CODE REVIEW

**Review by a-b-r-o-w-n — DISMISSED** [review]

**Comment by hatpick** [comment]
Let's make sure all is working before we merge this, I remember we were using 0.19.3 (it's now updated to 0.21.2)

**Comment by zhixzhan** [comment]
> Let's make sure all is working before we merge this, I remember we were using 0.19.3 (it's now updated to 0.21.2)

The reason of upgrading is we need the integrated `@monaco-editor/loader` from `@monaco-editor/react@3.8.3` and it requires `monaco-editor@^0.21.2`

I reviewed the changelog, no breaking changes in our usage.
https://github.com/suren-atoyan/monaco-react/blob/master/CHANGELOG.md
https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md

Sure, Let's wait for the customer's confirm.

**Comment by liweitian** [comment]
How about we fix this issue by copy the load.js locally? A user also says he cannot access the cdn from a VM. https://github.com/microsoft/BotFramework-Composer/pull/5547

**Comment by hatpick** [comment]
@zhixzhan let us know whenever you feel confident about this PR not breaking monaco API due to the version bump and we can merge it.

**Comment by zhixzhan** [comment]
@hatpick I test more scenario on 'Property Editor', 'All up view', 'Form Editor', 'JSON Editor', all looks good. I think we are ok to merge it.

**Review by hatpick — APPROVED** [review]

**Pull request merged**
