### PR TITLE
fix: Added missing dependencies to /types and /extensions packages.

### PR DESCRIPTION
**Pull request by tonyanziano**
## Description

`@bfc/extensions` and `@botframework-composer/types` have dependencies on `express-serve-static-core` but do not list it in their `package.json`

## Task Item

#minor

### CODE REVIEW

**Review by a-b-r-o-w-n — DISMISSED** [review]

**Comment by tonyanziano** [comment]
This caused some typechecks to break in `/server/` that need to be fixed.

**Comment by cwhitten** [comment]
@tonyanziano can you address conflicts plz

**Comment by tonyanziano** [comment]
Updated to fix typechecking errors.

**Review by a-b-r-o-w-n — DISMISSED** [review]

**Comment by tonyanziano** [comment]
need to fix a test that doesn't like one of the new types

**Review by a-b-r-o-w-n — APPROVED** [review]

**Pull request merged**
