### PR TITLE
chore: update archiver to fix security warning

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
## Description

Updates `archiver` to get security fix in `bl` dependency.

## Task Item

#minor

### CODE REVIEW

**Comment by a-b-r-o-w-n** [comment]
I've tested the code paths that use `archiver` on Mac and it works. Can I get someone with Windows to test these scenarios?

- export to zip
- local publish (start bot)
- publish to azure

**Comment by boydc2014** [comment]
@VanyLaw can you help test in windows for the above flow?

**Comment by VanyLaw** [comment]
Sure, I will test it

**Comment by VanyLaw** [comment]
@a-b-r-o-w-n I tested it on windows with echobot, all can pass.

**Review by boydc2014 — APPROVED** [review]

**Pull request merged**
