### PR TITLE
fix: unable to start bot in electron

### LINKED ISSUE #4472: Start bot failed due to some folder not found in nightly build Electron
## Describe the bug

Use the electron Composer to create the sample ToDoWithLuis bot and then click start the bot.

## Version

1.1.1-nightly.177231.e8d0d55

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Install the Electron version of 1.1.1-nightly.177231.e8d0d55
2. Create sample bot of ToDoWithLuis
3. Click start bot

## Expected behavior

No errors

## Screenshots

image

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
## Description

The root cause is changes about the expected path of the runtimes directory due to moving the extensions directory up a level. This moves the directory in the electron build to match the directory structure in the repo.

## Task Item

fixes #4472

### CODE REVIEW

**Comment by a-b-r-o-w-n** [comment]
I'm going to trigger a build off of this to test, so hold of on merging until then.

**Comment by a-b-r-o-w-n** [comment]
https://fuselabs.visualstudio.com/Composer/_build/results?buildId=177414&view=results

**Review by tonyanziano — APPROVED** [review]
👍

**Comment by a-b-r-o-w-n** [comment]
The build looks good. I'm going to merge.

**Pull request merged**
