### PR TITLE
fix: unable to clear form title

### LINKED ISSUE #2662: Weird editing behavior when rename a dialog
## Describe the bug
. In composer, new a trigger - dialog event
. Click the dialog name editbox to change the name "Dialog Started"
. BS to delete the whole name 

Result:
when BS and delete the whole dialog name, the name show again.

### LINKED ISSUE #2841: Send a response action gets created with Send an Activity as the name
Screen Shot 2020-04-29 at 4 32 27 PM
When a Send a response action gets created, the name field on the property pane says Send an Activity. But the node title says Send a response.

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**
## Description

This allows users to completely clear the form title. It will show the original title as a placeholder. If the user leaves that page and comes back, we will use the default heuristic to determine the title to use.

Also fixes an issue in the TodoLuis sample.

## Task Item

closes #2662 
closes #2841

# Screenshots

image
image

### CODE REVIEW

**Comment by cwhitten** [comment]
something has been lost on the subtitles

Screen Shot 2020-05-04 at 1 40 37 PM

this change exposes the raw definition key "Microsoft."

**Comment by a-b-r-o-w-n** [comment]
@beyackle that was a request by @sangwoohaan in #2845

**Comment by cwhitten** [comment]
@a-b-r-o-w-n it looks like a UT is failing

**Comment by a-b-r-o-w-n** [comment]
@cwhitten I forgot to update a snapshot. Hopefully the latest commit will pass CI.

**Pull request merged**
