### PR TITLE
feature: add /dashboard route with mockup

### PR DESCRIPTION
**Pull request by beyackle**
## Description

This adds the `/dashboard` route to the client, which for the moment just redirects to a rough mockup of the dashboard page. Nothing about the design here is intended to be final.

## Task Item

refs #3467 

## Screenshots

image

### CODE REVIEW

**Comment by srinaath** [comment]
As per our branching conversation last week we decided only shippable code enters master. Do we want a feature branch to track our work for multi bot with frequent rebasing with master?

**Comment by cwhitten** [comment]
> As per our branching conversation last week we decided only shippable code enters master. Do we want a feature branch to track our work for multi bot with frequent rebasing with master?

Yes this seems prudent. Perhaps we rebase this on the multi-bot feature branch.

**Comment by beyackle** [comment]
This is already based on the multibot feature branch.

**Comment by a-b-r-o-w-n** [comment]
@beyackle since this is targeting the multibot branch, is it good to merge?

**Comment by beyackle** [comment]
@a-b-r-o-w-n After the discussions we had last week about the multi-bot feature, I think I'm going to move this back into Draft status until the behaviors we want are more firmed up by design. This might need to close and be replaced by something, or it could be revised again, depending on what happens there.

**Pull request closed without merging**
