### PR TITLE
draft: Remote publish E2E prototype

### PR DESCRIPTION
**Pull request by boydc2014**
### Description
A follow up of the remote publish doc https://microsoft.sharepoint-df.com/:w:/r/teams/Composer/_layouts/15/Doc.aspx?sourcedoc=%7B0B524AA7-23E4-44BC-A0FC-9BD258232DA7%7D&file=Remote%20Publish%20from%20Composer.docx&wdOrigin=OFFICECOM-NTP.MAIN.REC&action=default&mobileredirect=true

This PR consists 3 parts
- [x] a local bot manager service that take over the runtime management and bot hosting
  - accept the http protocol and manage runtime in it's own space
  - support publish\history\rollback
  - support multiple bots at same time, port management, fast reload
- [x]  some publisher management in composer
   - a IPublisher interface
   - a HttpPublisher which creates publisher given a config
- [x] UX hook up in composer

### Architecture diagram
image

### Goals
1. Verify the approach that sperate the concern of runtime from composer, into dedicated runtime service would work
2. Figure out the details of the http publisher api
3. Figure out how much effort we need to have a runtime hosting service that implements those api
4. See how we can build a non-code(config-based) publisher system on top of a generic coding interface
5. Figure out how much we can\need to clean the core, how much abs-h specific code we've built
 
### Non-goal
- This PR touched some parts of how a publisher is registered and generally how a plugin get loaded and surfaced out through API. But not tended to be the standard.  

#### Stage1: replace BotProject1 with BotManagerService
- [ ] pass LUIS settings when publishing
- [ ] clean BotProject
- [ ] remove the copying runtime logic from composer core 
#### Stage2:  integrated in plugin system 
- [ ] hook in with plugin system
#### Stage3: cleanup and polish
- [ ] clean IEnvironment, IConnector, IEnvSettings
- [ ] publisher controller polish

### CODE REVIEW

**Comment by benbrown** [comment]
This looks great and is roughly in line with what I've been doing in the plugin loader.

@boydc2014 in my implementation, the loaded publishing mechanisms actually live in the PluginLoader service, rather than in the publishing service itself. It may be more appropriate for them to live in the publisher service -- but we will need to make sure it can be exposed to the plugin loader so that plugins can add new methods.

One key difference is that, in my current design, the configuration for each publishing endpoint will actually live in the bot settings. We may need a special case for local publish to test runtime, but in general, I believe these settings should be part of the bot configuration and NOT handled by the plugin or environment variables.

What I did in my prototype is, the user provides a configuration object via settings page that is bound to a specific method of publishing. Then, when the publish action is requested, Composer passes that configuration into the plugin to fulfill the request.  This enables a user to set up multiple publishing targets of the same type without installing multiple plugins -- for example, a dev, staging and production instance that differ only in their configuration.

**Comment by benbrown** [comment]
See also, #1945 and #1928

**Comment by boydc2014** [comment]
> This looks great and is roughly in line with what I've been doing in the plugin loader.
> 
> @boydc2014 in my implementation, the available publishing mechanisms live in the PluginLoader service, rather than in the publishing service itself. It may be more appropriate for them to live in the publisher service -- but we will need to make sure it can be exposed to the plugin loader so that plugins can add new methods.
> 
> One key difference is that, in my current design, the configuration for each publishing endpoint will actually live in the bot settings. We may need a special case for local publish to test runtime, but in general, I believe these settings should be part of the bot configuration and NOT handled by the plugin or environment variables.
> 
> What I did in my prototype is, the user provides a configuration object via settings page that is bound to a specific method of publishing. Then, when the publish action is requested, Composer passes that configuration into the plugin to fulfill the request. This enables a user to set up multiple publishing targets of the same type without installing multiple plugins -- for example, a dev, staging and production instance that differ only in their configuration.

I think we are on the same page even for the key difference you mentioned, my thought is we have a IPublisher *coding* interface for plugin, then I have a HttpPublisher to create HttpPublisher via config,  there is another type of IPublisher that may load from local plugin folder.

In the case of HttpGenerator, i use multiple config will generate multiple HttpPublisher, see the code in PublisherService.init(), which allow user to publish with different target without have to modify config, user are creating multiple plugin(Ipublisher) in my case, by it's created very lightweight, the `HttpPublisher` serve as a "PublisherGenerator" in this case. 

It's not ready yet, i plan to complete it to some degree, and reach out to you and folks to review it later, probably next week, and the implementation is not to be production, mainly focus exploration on the protocol.

**Comment by boydc2014** [comment]
@benbrown  I read through your comments here and in your PR, and re-clarify the goals and non-goals of this PR in the description above, to make sure this PR focusing on run time decoupling, publishing protocol evaluation and implementation and other relate refinement on the composer core ifself. Leave out the plugin loading and managing as a non-goal, and let us seek for a good approach works for all scenarios we are targeting now.

**Comment by lei9444** [comment]
update some ux
ui

**Comment by boydc2014** [comment]
Close this, since this PR reach its goal, the follow up will be a local plugin which separate the concern of runtime from Composer core

**Pull request closed without merging**
