### PR TITLE
doc: update/provision+publish/readmes

### PR DESCRIPTION
**Pull request by zxyanliu**
## Description

Revise the provision and publish README files.

* Provision (using JavaScript scripts): https://github.com/microsoft/BotFramework-Composer/blob/main/extensions/samples/assets/shared/README.md
* Publish (using PowerShell scripts): https://github.com/microsoft/BotFramework-Composer/tree/main/runtime/dotnet/azurewebapp/Scripts

Closing:

- https://github.com/microsoft/BotFramework-Composer/issues/5773

#minor

### CODE REVIEW

**Comment by zxyanliu** [comment]
To: @luhan2017 @zidaneymar 
cc: @cwhitten @hibrenda
The two readme files are almost done. I am pasting the known issues for possible fixes:

1. After running the provision scripts, the command line cannot exit automatically. You need to press `control+c` to exit.
   
   image

2. When running the deploy scripts, there are cross-train errors.

   image

3. The current deploy scripts take a very long time to complete. (more than 10 mins)

4. After the deploy scripts complete, the directory defaults to the following: 
    `C:\Users\v-liyan\Desktop\Bots\EchoBot-218\runtime\azurewebapp\bin\Release\netcoreapp3.1\ComposerDialogs`
   
5. A couple of known issues to confirm: 
    1. The provision and publish flow using Composer UI is limited to Microsoft/Azure organization account. A personal Azure account will not make authentication work. 
    2. The provision and publish flow using scripts (not flow Composer UI) is limited to Microsoft/Azure organization account. A personal Azure account will not make authentication work. 
    3. Composer does not support switching b/w different Azure directories/subscriptions. 
    4. Composer does not support interactive signing to the Azure portal.
  
Please let me know if I missed anything. Thanks!

**Comment by luhan2017** [comment]
Thanks @zxyanliu for this great summary. I will follow up 1,2,3,4 issues with @zidaneymar , we will update later.

For 5: A couple of known issues to confirm:

    1. The provision and publish flow using Composer UI is limited to Microsoft/Azure organization account. A personal Azure account will not make authentication work. [That is true now, but we are very close, I will follow up with Tony to fix this.]
    2. The provision and publish flow using scripts (not flow Composer UI) is limited to Microsoft/Azure organization account. A personal Azure account will not make authentication work. [No, personal account should work for scripts]
    3. Composer does not support switching b/w different Azure directories/subscriptions. [Yes, this is only for Composer, scripts supports switch between directories/subscriptions, az account set --subscription ******]
    4. Composer does not support interactive signing to the Azure portal. [I am not sure if I understand this correctly, the interactive signin is only needed for specific users, we can't get the token silently from oneauth package, I will follow up with Tony on this part]
    5. Composer does not support in-app signing into Azure Government Cloud. Needs additional workarounds. https://github.com/microsoft/BotFramework-Composer/issues/5613  [The issue is just saying that the runtime needs to be customized to support government cloud, I don't have an account for Azure Government Cloud, we can sync up offline to double check on this using your account.]

**Comment by zxyanliu** [comment]
@luhan2017 @zidaneymar Can you guys take a look at this PR, especially the parameters lists of the provision scripts and the publish scripts? We target to make the content available before R12, if possible. Thanks a lot!

**Comment by zidaneymar** [comment]
> To: @luhan2017 @zidaneymar
> cc: @cwhitten @hibrenda
> The two readme files are almost done. I am pasting the known issues for possible fixes:
> 
> 1. After running the provision scripts, the command line cannot exit automatically. You need to press `control+c` to exit.
>    image
> 2. When running the deploy scripts, there are cross-train errors.
>    image
> 3. The current deploy scripts take a very long time to complete. (more than 10 mins compared with in-app provision and publish which usually take less than 2 mins)
> 4. After the deploy scripts complete, the directory defaults to the following:
>    `C:\Users\v-liyan\Desktop\Bots\EchoBot-218\runtime\azurewebapp\bin\Release\netcoreapp3.1\ComposerDialogs`
> 5. A couple of known issues to confirm:
>    
>    1. The provision and publish flow using Composer UI is limited to Microsoft/Azure organization account. A personal Azure account will not make authentication work.
>    2. The provision and publish flow using scripts (not flow Composer UI) is limited to Microsoft/Azure organization account. A personal Azure account will not make authentication work.
>    3. Composer does not support switching b/w different Azure directories/subscriptions.
>    4. Composer does not support interactive signing to the Azure portal.
>    5. Composer does not support in-app signing into Azure Government Cloud. Needs additional workarounds. #5613
> 
> Please let me know if I missed anything. Thanks!

I want to confirm that for step 2:
It seems that crosstrain.config.json is not generated correctly. This is not a script issue but a composer issue, could you please recreate a bot and try again

**Comment by zidaneymar** [comment]
```
1.After running the provision scripts, the command line cannot exit automatically. You need to press control+c to exit.
```
for this issue, I can't repro this through vscode debugger.

**Comment by luhan2017** [comment]
> ```
> 1.After running the provision scripts, the command line cannot exit automatically. You need to press control+c to exit.
> ```
> 
> for this issue, I can't repro this through vscode debugger.

I can reproduce it in the command line tool, let's sync up on this offline.

**Comment by zidaneymar** [comment]
Issue 2 and 4 are fixed.

**Review by luhan2017 — APPROVED** [review]

**Pull request merged**
