### PR TITLE
fix: Functions runtime: Revert to netcore3.0 for functions and make code more robust to functions variations

### LINKED ISSUE #4243: Unable to execute the bot on Azure functions
## Describe the bug
Upon publishing the bot to Azure function, the Azure function goes down and doesnt respond to any request

I have followed the steps for publishing bot to Azure Function with resources created through the command line script

The Function App shows up the below error
image

And the status of the runtime shows as error
image

And the diagnosis says
image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

## Version
1.1.1

## Browser
Chrome

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Follow steps for Azure function as provided here
https://docs.microsoft.com/en-us/composer/how-to-publish-bot

## Expected behavior
The function should not error and the bot should reply over the bot channel registration test panel

## Screenshots
Added above at relevant place

## Additional context
The function apps were created through the commandline script as provided in the documentation

### PR DESCRIPTION
**Pull request by carlosscastro**
## Description

Fix runtime to work properly when deployed to azure functions:

- Main issue was netcore runtime was moved to 3.1 but there are known issues with FunctionsStartup and 3.1, so here I revert back to 3.0
- Remove unnecessary references
- Improve robustness of detection of asset folder. Playing with the target runtime of my function app I found ways to break asset discovery. The current code is a bit more robust to structural changes to the directory tree (even though there are lots of things to improve in startup, but keeping the PR targeted to funcitons fix)

## Task Item

Closes #4243 

## Screenshots

After runtime changes, I can publish to functions

image

And the bot works fine in azure

image

### CODE REVIEW

**Review by luhan2017 — APPROVED** [review]
I tried this branch and it works perfectly.

**Comment by luhan2017** [comment]
One side topic, do we want to support AllowedCallersClaimsValidator in AF? and do we still want to add a preview tag to Azure Functions?

**Comment by carlosscastro** [comment]
I'd leave functions as preview since they don't support being skill hosts, just skills. Supporting being a skill host requires a bit of delicate work with functions http routing and not sure there is value in it considering we'll replace that bit in R12. I may be able to look into this but not guaranteed. Regarding validators -- true, we should port the validators change to functions and also to js (web app and functions). @luhan2017, could you create work items for that and assign accordingly? Thanks :) And thanks for verifying the current change!

**Comment by carlosscastro** [comment]
unit test failures seem unrelated. @luhan2017 do you happen to know if these failures are being investigated on main?

**Comment by luhan2017** [comment]
> unit test failures seem unrelated. @luhan2017 do you happen to know if these failures are being investigated on main?

Yes, this should be an issue in main branch, we had a PR for that, I will follow up this.

**Pull request merged**
